global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
rule_files:
  - /etc/rules.yml
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: storage
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /storage/metrics
  scheme: http
  static_configs:
  - targets:
    - cloudStorage:9090
