defaultEntryPoints = ["http","https"]
RootCAs = [ "/certs/ca.pem" ]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/certs/traefik.pem"
      KeyFile = "/certs/traefik-key.pem"

[web]
address = ":8080"

[file]

[backends]
  [backends.localauth]
    [backends.localauth.servers.server1]
    url = "https://localAuth"

  [backends.localauthMetrics]
    [backends.localauthMetrics.servers.server1]
    url = "http://localAuth:9090"

  [backends.localauthStatus]
    [backends.localauthStatus.servers.server1]
    url = "http://localAuth:4433"

  [backends.cloudauth]
    [backends.cloudauth.servers.server1]
    url = "https://cloudAuth"
    weight = 10

  [backends.cloudauthStatus]
    [backends.cloudauthStatus.servers.server1]
    url = "http://cloudAuth:4433"

  [backends.cloudauthMetrics]
    [backends.cloudauthMetrics.servers.server1]
    url = "http://cloudAuth:9090"

  [backends.localstorage]
    [backends.localstorage.servers.server1]
    url = "https://localStorage"

  [backends.localstorageMetrics]
    [backends.localstorageMetrics.servers.server1]
    url = "http://localStorage:9090"

  [backends.localstorageStatus]
    [backends.localstorageStatus.servers.server1]
    url = "https://localStorage:4433"

  [backends.waitlist]
    [backends.waitlist.servers.server1]
    url = "https://waitlist"

  [backends.waitlistMetrics]
    [backends.waitlistMetrics.servers.server1]
    url = "https://waitlist:9090"

  [backends.waitlistStatus]
    [backends.waitlistStatus.servers.server1]
    url = "https://waitlist:4433"

  [backends.localMinio]
    [backends.localMinio.servers.server1]
    url = "https://localMinio:9000"

  [backends.cloudstorage]
    [backends.cloudstorage.servers.server1]
    url = "https://cloudStorage"

  [backends.cloudstorageMetrics]
    [backends.cloudstorageMetrics.servers.server1]
    url = "http://cloudStorage:9090"

  [backends.cloudstorageStatus]
    [backends.cloudstorageStatus.servers.server1]
    url = "https://cloudStorage:4433"

  [backends.cloudMinio]
    [backends.cloudMinio.servers.server1]
    url = "https://cloudMinio:9000"

  [backends.vaultui]
    [backends.vaultui.servers.server1]
    url = "http://vaultui:8000"

  [backends.localNats]
    [backends.localNats.servers.server1]
    url = "http://localNats:4242"

  [backends.localNatsMonitor]
    [backends.localNatsMonitor.servers.server1]
    url = "http://localNats:8282"

  [backends.localPrometheus]
    [backends.localPrometheus.servers.server1]
    url = "http://localPrometheus:9090"

  [backends.cloudPrometheus]
    [backends.cloudPrometheus.servers.server1]
    url = "http://cloudPrometheus:9090"

  [backends.natsStreamingMetricsExporter]
    [backends.natsStreamingMetricsExporter.servers.server1]
    url = "http://natsStreamingExporter:9275"

  [backends.storagesyncMetrics]
    [backends.storagesyncMetrics.servers.server1]
    url = "http://storageSync:9090"

  [backends.storagesyncStatus]
    [backends.storagesyncStatus.servers.server1]
    url = "http://storageSync:4433"

  [backends.localPrometheusPushGateway]
    [backends.localPrometheusPushGateway.servers.server1]
    url = "http://localPrometheusPushGateway:9091"

  [backends.localStatusReporter]
    [backends.localStatusReporter.servers.server1]
    url = "https://localStatusReporter"

  [backends.localStatusReporterMetrics]
    [backends.localStatusReporterMetrics.servers.server1]
    url = "http://localStatusReporterMetrics:9090"

  [backends.cloudStatusReporter]
    [backends.cloudStatusReporter.servers.server1]
    url = "https://cloudStatusReporter"

  [backends.cloudStatusReporterMetrics]
    [backends.cloudStatusReporterMetrics.servers.server1]
    url = "http://cloudStatusReporterMetrics:9090"

  [backends.localdiscovery]
    [backends.localdiscovery.servers.server1]
    url = "https://localDiscovery"

  [backends.localdiscoveryMetrics]
    [backends.localdiscoveryMetrics.servers.server1]
    url = "https://localDiscovery:9090"

  [backends.clouddiscovery]
    [backends.clouddiscovery.servers.server1]
    url = "https://cloudDiscovery"

  [backends.clouddiscoveryMetrics]
    [backends.clouddiscoveryMetrics.servers.server1]
    url = "https://cloudDiscovery:9090"

  [backends.pgweb]
    [backends.pgweb.servers.server1]
    url = "http://pgweb:8081"

[frontends]
  [frontends.localauth]
  backend = "localauth"
    [frontends.localauth.routes.route1]
    rule = "Host:iryo.local;PathPrefix:/auth"

  [frontends.localstorage]
  backend = "localstorage"
    [frontends.localstorage.routes.route1]
    rule = "Host:iryo.local;PathPrefix:/storage"

  [frontends.cloudauth]
  backend = "cloudauth"
    [frontends.cloudauth.routes.route1]
    rule = "Host:iryo.cloud;PathPrefix:/auth"

  [frontends.localstorageMetrics]
  backend = "localstorageMetrics"
    [frontends.localstorageMetrics.routes.route1]
    rule = "Host:iryo.local;PathPrefix:/storage/metrics"

  [frontends.waitlist]
  backend = "waitlist"
    [frontends.waitlist.routes.route1]
    rule = "Host:iryo.local;PathPrefix:/waitlist"

  [frontends.localMinio]
  backend = "localMinio"
    [frontends.localMinio.routes.route1]
    rule = "Host:minio.iryo.local"

  [frontends.cloudstorage]
  backend = "cloudstorage"
    [frontends.cloudstorage.routes.route1]
    rule = "Host:iryo.cloud;PathPrefix:/storage"

  [frontends.cloudMinio]
  backend = "cloudMinio"
    [frontends.cloudMinio.routes.route1]
    rule = "Host:minio.iryo.cloud"

  [frontends.vaultui]
  backend = "vaultui"
    [frontends.vaultui.routes.route1]
    rule = "Host:vault.iryo.local"

  [frontends.localNats]
  backend = "localNats"
    [frontends.localNats.routes.route1]
    rule = "Host:nats.iryo.local"

  [frontends.localNatsMonitor]
  backend = "localNatsMonitor"
    [frontends.localNatsMonitor.routes.route1]
    rule = "Host:nats-monitor.iryo.local"

  [frontends.localPrometheus]
  backend = "localPrometheus"
    [frontends.localPrometheus.routes.route1]
    rule = "Host:prometheus.iryo.local"

  [frontends.cloudPrometheus]
  backend = "cloudPrometheus"
    [frontends.cloudPrometheus.routes.route1]
    rule = "Host:prometheus.iryo.cloud"

  [frontends.localStatus]
  backend = "localStatusReporter"
    [frontends.localStatus.routes.route1]
    rule = "Host:iryo.local;PathPrefix:/status"

  [frontends.cloudStatus]
  backend = "cloudStatusReporter"
    [frontends.cloudStatus.routes.route1]
    rule = "Host:iryo.cloud;PathPrefix:/status"

  [frontends.localdiscovery]
  backend = "localdiscovery"
    [frontends.localdiscovery.routes.route1]
    rule = "Host:iryo.local;PathPrefix:/discovery"

  [frontends.clouddiscovery]
  backend = "clouddiscovery"
    [frontends.clouddiscovery.routes.route1]
    rule = "Host:iryo.cloud;PathPrefix:/discovery"

  [frontends.pgweb]
  backend = "pgweb"
    [frontends.pgweb.routes.route1]
    rule = "Host:pgweb.iryo.local"
