## development values for traefik
imageTag: 1.7
debug:
  enabled: true
ssl:
  enabled: true
  enforced: true
  insecureSkipVerify: false
  certificates:
    - type: secret
      name: ca-iryo-local
    - type: secret
      name: ca-iryo-cloud
  rootCAs:
    - type: secret
      name: ca-key-pair
dashboard:
  enabled: true
  domain: traefik-dashboard.k8s.local
rbac:
  enabled: true
sendAnonymousUsage: false
