// Code generated by protoc-gen-go.
// source: accountManager.proto
// DO NOT EDIT!

/*
Package specs is a generated protocol buffer package.

It is generated from these files:
	accountManager.proto
	authenticator.proto
	common.proto

It has these top-level messages:
	GetUsersRequest
	GetACLRulesRequest
	User
	ACLRule
	LoginRequest
	LoginResponse
	ValidationPair
	ValidationResult
	ValidationRequest
	ValidationResponse
	Empty
	ErrorResponse
*/
package specs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUsersRequest struct {
	Error  ErrorCode `protobuf:"varint,1,opt,name=error,enum=specs.ErrorCode" json:"error,omitempty"`
	Search string    `protobuf:"bytes,2,opt,name=search" json:"search,omitempty"`
}

func (m *GetUsersRequest) Reset()                    { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()               {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetUsersRequest) GetError() ErrorCode {
	if m != nil {
		return m.Error
	}
	return ErrorCode_OK
}

func (m *GetUsersRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type GetACLRulesRequest struct {
	Error    ErrorCode       `protobuf:"varint,1,opt,name=error,enum=specs.ErrorCode" json:"error,omitempty"`
	UserID   string          `protobuf:"bytes,2,opt,name=userID" json:"userID,omitempty"`
	Resource string          `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	Actions  []ACLRuleAction `protobuf:"varint,4,rep,packed,name=actions,enum=specs.ACLRuleAction" json:"actions,omitempty"`
}

func (m *GetACLRulesRequest) Reset()                    { *m = GetACLRulesRequest{} }
func (m *GetACLRulesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetACLRulesRequest) ProtoMessage()               {}
func (*GetACLRulesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetACLRulesRequest) GetError() ErrorCode {
	if m != nil {
		return m.Error
	}
	return ErrorCode_OK
}

func (m *GetACLRulesRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetACLRulesRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *GetACLRulesRequest) GetActions() []ACLRuleAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

func init() {
	proto.RegisterType((*GetUsersRequest)(nil), "specs.GetUsersRequest")
	proto.RegisterType((*GetACLRulesRequest)(nil), "specs.GetACLRulesRequest")
}

func init() { proto.RegisterFile("accountManager.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x8f, 0x5d, 0x4a, 0x43, 0x31,
	0x10, 0x85, 0xb9, 0xd6, 0x56, 0x0d, 0x52, 0x25, 0xfe, 0x10, 0xee, 0xd3, 0xa5, 0x0f, 0x72, 0x9f,
	0x22, 0xd4, 0x15, 0x48, 0x95, 0x22, 0xe8, 0x83, 0x01, 0x17, 0x10, 0xc7, 0xc1, 0x16, 0x6c, 0xa6,
	0xce, 0x4c, 0x16, 0xe4, 0x4e, 0xc5, 0x9b, 0xd4, 0x05, 0xf4, 0xf1, 0x9c, 0xef, 0xf0, 0x31, 0x63,
	0x2e, 0x23, 0x00, 0xe5, 0xa4, 0x2f, 0x31, 0xc5, 0x4f, 0x64, 0xbf, 0x65, 0x52, 0xb2, 0x63, 0xd9,
	0x22, 0x48, 0x7b, 0x0a, 0xb4, 0xd9, 0x50, 0x2a, 0x65, 0x7b, 0x11, 0xb3, 0xae, 0x30, 0xe9, 0x1a,
	0xa2, 0x52, 0x5d, 0xce, 0x5e, 0xcd, 0xd9, 0x12, 0xf5, 0x4d, 0x90, 0x25, 0xe0, 0x77, 0x46, 0x51,
	0x7b, 0x63, 0xc6, 0xc8, 0x4c, 0xec, 0x9a, 0xae, 0xe9, 0xa7, 0xf3, 0x73, 0x3f, 0xc8, 0xfc, 0xe3,
	0x5f, 0xb7, 0xa0, 0x0f, 0x0c, 0x05, 0xdb, 0x6b, 0x33, 0x11, 0x8c, 0x0c, 0x2b, 0x77, 0xd0, 0x35,
	0xfd, 0x49, 0xa8, 0x69, 0xf6, 0xd3, 0x18, 0xbb, 0x44, 0xbd, 0x5f, 0x3c, 0x87, 0xfc, 0x85, 0xfb,
	0x68, 0xb3, 0x20, 0x3f, 0x3d, 0xec, 0xb4, 0x25, 0xd9, 0xd6, 0x1c, 0x33, 0x0a, 0x65, 0x06, 0x74,
	0xa3, 0x81, 0xfc, 0x67, 0x7b, 0x6b, 0x8e, 0x22, 0xe8, 0x9a, 0x92, 0xb8, 0xc3, 0x6e, 0xd4, 0x4f,
	0xe7, 0x57, 0xd5, 0x5e, 0x8f, 0xf0, 0x85, 0x86, 0xdd, 0xea, 0x7d, 0x32, 0x7c, 0x7f, 0xf7, 0x1b,
	0x00, 0x00, 0xff, 0xff, 0xbd, 0x53, 0x0d, 0xa9, 0x3f, 0x01, 0x00, 0x00,
}
