// Code generated by protoc-gen-go.
// source: common.proto
// DO NOT EDIT!

/*
Package specs is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	Empty
*/
package specs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_OK ErrorCode = 0
)

var ErrorCode_name = map[int32]string{
	0: "OK",
}
var ErrorCode_value = map[string]int32{
	"OK": 0,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Empty struct {
	Error ErrorCode `protobuf:"varint,1,opt,name=error,enum=specs.ErrorCode" json:"error,omitempty"`
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Empty) GetError() ErrorCode {
	if m != nil {
		return m.Error
	}
	return ErrorCode_OK
}

func init() {
	proto.RegisterType((*Empty)(nil), "specs.Empty")
	proto.RegisterEnum("specs.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x2e, 0x48, 0x4d, 0x2e, 0x56,
	0xd2, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x14, 0x52, 0xe3, 0x62, 0x4d, 0x2d, 0x2a, 0xca,
	0x2f, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x12, 0xd0, 0x03, 0xcb, 0xeb, 0xb9, 0x82, 0xc4,
	0x9c, 0xf3, 0x53, 0x52, 0x83, 0x20, 0xd2, 0x5a, 0xc2, 0x5c, 0x9c, 0x70, 0x31, 0x21, 0x36, 0x2e,
	0x26, 0x7f, 0x6f, 0x01, 0x86, 0x24, 0x36, 0xb0, 0x99, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x82, 0x1f, 0x1d, 0xd0, 0x63, 0x00, 0x00, 0x00,
}
