-- patients
INSERT INTO patients (patient_id) VALUES ('554ec907-9f86-4abf-a1fb-7ec211c22611');
INSERT INTO patients (patient_id) VALUES ('ea925eba-98c1-4708-a6b6-c337dfa45900');

-- patient connections
INSERT INTO connections (patient_id, key, value) VALUES ('554ec907-9f86-4abf-a1fb-7ec211c22611', 'name', 'Local User');
INSERT INTO connections (patient_id, key, value) VALUES ('ea925eba-98c1-4708-a6b6-c337dfa45900', 'name', 'Cloud User');

-- patient locations
INSERT INTO locations (patient_id, location_id) VALUES ('554ec907-9f86-4abf-a1fb-7ec211c22611', '2d04b22e-1cc3-46b4-96dd-2bee5bad9ffa');
INSERT INTO locations (patient_id, location_id) VALUES ('ea925eba-98c1-4708-a6b6-c337dfa45900', 'f7e41e48-ec79-4c78-9db6-37c0c4f78326');

-- codes
INSERT INTO codes (category_id, code_id) VALUES
    ('countries', 'AF'),
    ('countries', 'AX'),
    ('countries', 'AL'),
    ('countries', 'DZ'),
    ('countries', 'AS'),
    ('countries', 'AD'),
    ('countries', 'AO'),
    ('countries', 'AI'),
    ('countries', 'AQ'),
    ('countries', 'AG'),
    ('countries', 'AR'),
    ('countries', 'AM'),
    ('countries', 'AW'),
    ('countries', 'AU'),
    ('countries', 'AT'),
    ('countries', 'AZ'),
    ('countries', 'BS'),
    ('countries', 'BH'),
    ('countries', 'BD'),
    ('countries', 'BB'),
    ('countries', 'BY'),
    ('countries', 'BE'),
    ('countries', 'BZ'),
    ('countries', 'BJ'),
    ('countries', 'BM'),
    ('countries', 'BT'),
    ('countries', 'BO'),
    ('countries', 'BA'),
    ('countries', 'BW'),
    ('countries', 'BV'),
    ('countries', 'BR'),
    ('countries', 'VG'),
    ('countries', 'IO'),
    ('countries', 'BN'),
    ('countries', 'BG'),
    ('countries', 'BF'),
    ('countries', 'BI'),
    ('countries', 'KH'),
    ('countries', 'CM'),
    ('countries', 'CA'),
    ('countries', 'CV'),
    ('countries', 'KY'),
    ('countries', 'CF'),
    ('countries', 'TD'),
    ('countries', 'CL'),
    ('countries', 'CN'),
    ('countries', 'HK'),
    ('countries', 'MO'),
    ('countries', 'CX'),
    ('countries', 'CC'),
    ('countries', 'CO'),
    ('countries', 'KM'),
    ('countries', 'CG'),
    ('countries', 'CD'),
    ('countries', 'CK'),
    ('countries', 'CR'),
    ('countries', 'CI'),
    ('countries', 'HR'),
    ('countries', 'CU'),
    ('countries', 'CY'),
    ('countries', 'CZ'),
    ('countries', 'DK'),
    ('countries', 'DJ'),
    ('countries', 'DM'),
    ('countries', 'DO'),
    ('countries', 'EC'),
    ('countries', 'EG'),
    ('countries', 'SV'),
    ('countries', 'GQ'),
    ('countries', 'ER'),
    ('countries', 'EE'),
    ('countries', 'ET'),
    ('countries', 'FK'),
    ('countries', 'FO'),
    ('countries', 'FJ'),
    ('countries', 'FI'),
    ('countries', 'FR'),
    ('countries', 'GF'),
    ('countries', 'PF'),
    ('countries', 'TF'),
    ('countries', 'GA'),
    ('countries', 'GM'),
    ('countries', 'GE'),
    ('countries', 'DE'),
    ('countries', 'GH'),
    ('countries', 'GI'),
    ('countries', 'GR'),
    ('countries', 'GL'),
    ('countries', 'GD'),
    ('countries', 'GP'),
    ('countries', 'GU'),
    ('countries', 'GT'),
    ('countries', 'GG'),
    ('countries', 'GN'),
    ('countries', 'GW'),
    ('countries', 'GY'),
    ('countries', 'HT'),
    ('countries', 'HM'),
    ('countries', 'VA'),
    ('countries', 'HN'),
    ('countries', 'HU'),
    ('countries', 'IS'),
    ('countries', 'IN'),
    ('countries', 'ID'),
    ('countries', 'IR'),
    ('countries', 'IQ'),
    ('countries', 'IE'),
    ('countries', 'IM'),
    ('countries', 'IL'),
    ('countries', 'IT'),
    ('countries', 'JM'),
    ('countries', 'JP'),
    ('countries', 'JE'),
    ('countries', 'JO'),
    ('countries', 'KZ'),
    ('countries', 'KE'),
    ('countries', 'KI'),
    ('countries', 'KP'),
    ('countries', 'KR'),
    ('countries', 'KW'),
    ('countries', 'KG'),
    ('countries', 'LA'),
    ('countries', 'LV'),
    ('countries', 'LB'),
    ('countries', 'LS'),
    ('countries', 'LR'),
    ('countries', 'LY'),
    ('countries', 'LI'),
    ('countries', 'LT'),
    ('countries', 'LU'),
    ('countries', 'MK'),
    ('countries', 'MG'),
    ('countries', 'MW'),
    ('countries', 'MY'),
    ('countries', 'MV'),
    ('countries', 'ML'),
    ('countries', 'MT'),
    ('countries', 'MH'),
    ('countries', 'MQ'),
    ('countries', 'MR'),
    ('countries', 'MU'),
    ('countries', 'YT'),
    ('countries', 'MX'),
    ('countries', 'FM'),
    ('countries', 'MD'),
    ('countries', 'MC'),
    ('countries', 'MN'),
    ('countries', 'ME'),
    ('countries', 'MS'),
    ('countries', 'MA'),
    ('countries', 'MZ'),
    ('countries', 'MM'),
    ('countries', 'NA'),
    ('countries', 'NR'),
    ('countries', 'NP'),
    ('countries', 'NL'),
    ('countries', 'AN'),
    ('countries', 'NC'),
    ('countries', 'NZ'),
    ('countries', 'NI'),
    ('countries', 'NE'),
    ('countries', 'NG'),
    ('countries', 'NU'),
    ('countries', 'NF'),
    ('countries', 'MP'),
    ('countries', 'NO'),
    ('countries', 'OM'),
    ('countries', 'PK'),
    ('countries', 'PW'),
    ('countries', 'PS'),
    ('countries', 'PA'),
    ('countries', 'PG'),
    ('countries', 'PY'),
    ('countries', 'PE'),
    ('countries', 'PH'),
    ('countries', 'PN'),
    ('countries', 'PL'),
    ('countries', 'PT'),
    ('countries', 'PR'),
    ('countries', 'QA'),
    ('countries', 'RE'),
    ('countries', 'RO'),
    ('countries', 'RU'),
    ('countries', 'RW'),
    ('countries', 'BL'),
    ('countries', 'SH'),
    ('countries', 'KN'),
    ('countries', 'LC'),
    ('countries', 'MF'),
    ('countries', 'PM'),
    ('countries', 'VC'),
    ('countries', 'WS'),
    ('countries', 'SM'),
    ('countries', 'ST'),
    ('countries', 'SA'),
    ('countries', 'SN'),
    ('countries', 'RS'),
    ('countries', 'SC'),
    ('countries', 'SL'),
    ('countries', 'SG'),
    ('countries', 'SK'),
    ('countries', 'SI'),
    ('countries', 'SB'),
    ('countries', 'SO'),
    ('countries', 'ZA'),
    ('countries', 'GS'),
    ('countries', 'SS'),
    ('countries', 'ES'),
    ('countries', 'LK'),
    ('countries', 'SD'),
    ('countries', 'SR'),
    ('countries', 'SJ'),
    ('countries', 'SZ'),
    ('countries', 'SE'),
    ('countries', 'CH'),
    ('countries', 'SY'),
    ('countries', 'TW'),
    ('countries', 'TJ'),
    ('countries', 'TZ'),
    ('countries', 'TH'),
    ('countries', 'TL'),
    ('countries', 'TG'),
    ('countries', 'TK'),
    ('countries', 'TO'),
    ('countries', 'TT'),
    ('countries', 'TN'),
    ('countries', 'TR'),
    ('countries', 'TM'),
    ('countries', 'TC'),
    ('countries', 'TV'),
    ('countries', 'UG'),
    ('countries', 'UA'),
    ('countries', 'AE'),
    ('countries', 'GB'),
    ('countries', 'US'),
    ('countries', 'UM'),
    ('countries', 'UY'),
    ('countries', 'UZ'),
    ('countries', 'VU'),
    ('countries', 'VE'),
    ('countries', 'VN'),
    ('countries', 'VI'),
    ('countries', 'WF'),
    ('countries', 'EH'),
    ('countries', 'YE'),
    ('countries', 'ZM'),
    ('countries', 'ZW'),

    ('languages', 'abk'),
    ('languages', 'ace'),
    ('languages', 'ach'),
    ('languages', 'ada'),
    ('languages', 'ady'),
    ('languages', 'ady'),
    ('languages', 'aar'),
    ('languages', 'afh'),
    ('languages', 'afr'),
    ('languages', 'afa'),
    ('languages', 'ain'),
    ('languages', 'aka'),
    ('languages', 'akk'),
    ('languages', 'alb'),
    ('languages', 'gsw'),
    ('languages', 'ale'),
    ('languages', 'alg'),
    ('languages', 'gsw'),
    ('languages', 'tut'),
    ('languages', 'amh'),
    ('languages', 'anp'),
    ('languages', 'apa'),
    ('languages', 'ara'),
    ('languages', 'arg'),
    ('languages', 'arp'),
    ('languages', 'arw'),
    ('languages', 'arm'),
    ('languages', 'rup'),
    ('languages', 'art'),
    ('languages', 'rup'),
    ('languages', 'asm'),
    ('languages', 'ast'),
    ('languages', 'ast'),
    ('languages', 'ath'),
    ('languages', 'aus'),
    ('languages', 'map'),
    ('languages', 'ava'),
    ('languages', 'ave'),
    ('languages', 'awa'),
    ('languages', 'aym'),
    ('languages', 'aze'),
    ('languages', 'ast'),
    ('languages', 'ban'),
    ('languages', 'bat'),
    ('languages', 'bal'),
    ('languages', 'bam'),
    ('languages', 'bai'),
    ('languages', 'bad'),
    ('languages', 'bnt'),
    ('languages', 'bas'),
    ('languages', 'bak'),
    ('languages', 'baq'),
    ('languages', 'btk'),
    ('languages', 'bej'),
    ('languages', 'bej'),
    ('languages', 'bel'),
    ('languages', 'bem'),
    ('languages', 'ben'),
    ('languages', 'ber'),
    ('languages', 'bho'),
    ('languages', 'bih'),
    ('languages', 'bik'),
    ('languages', 'byn'),
    ('languages', 'bin'),
    ('languages', 'bis'),
    ('languages', 'byn'),
    ('languages', 'zbl'),
    ('languages', 'zbl'),
    ('languages', 'zbl'),
    ('languages', 'nob'),
    ('languages', 'bos'),
    ('languages', 'bra'),
    ('languages', 'bre'),
    ('languages', 'bug'),
    ('languages', 'bul'),
    ('languages', 'bua'),
    ('languages', 'bur'),
    ('languages', 'cad'),
    ('languages', 'spa'),
    ('languages', 'cat'),
    ('languages', 'cau'),
    ('languages', 'ceb'),
    ('languages', 'cel'),
    ('languages', 'cai'),
    ('languages', 'khm'),
    ('languages', 'chg'),
    ('languages', 'cmc'),
    ('languages', 'cha'),
    ('languages', 'che'),
    ('languages', 'chr'),
    ('languages', 'nya'),
    ('languages', 'chy'),
    ('languages', 'chb'),
    ('languages', 'nya'),
    ('languages', 'chi'),
    ('languages', 'chn'),
    ('languages', 'chp'),
    ('languages', 'cho'),
    ('languages', 'zha'),
    ('languages', 'chu'),
    ('languages', 'chu'),
    ('languages', 'chk'),
    ('languages', 'chv'),
    ('languages', 'nwc'),
    ('languages', 'nwc'),
    ('languages', 'syc'),
    ('languages', 'rar'),
    ('languages', 'cop'),
    ('languages', 'cor'),
    ('languages', 'cos'),
    ('languages', 'cre'),
    ('languages', 'mus'),
    ('languages', 'crp'),
    ('languages', 'cpe'),
    ('languages', 'cpf'),
    ('languages', 'cpp'),
    ('languages', 'crh'),
    ('languages', 'crh'),
    ('languages', 'hrv'),
    ('languages', 'cus'),
    ('languages', 'cze'),
    ('languages', 'dak'),
    ('languages', 'dan'),
    ('languages', 'dar'),
    ('languages', 'del'),
    ('languages', 'chp'),
    ('languages', 'div'),
    ('languages', 'zza'),
    ('languages', 'zza'),
    ('languages', 'din'),
    ('languages', 'div'),
    ('languages', 'doi'),
    ('languages', 'dgr'),
    ('languages', 'dra'),
    ('languages', 'dua'),
    ('languages', 'dut'),
    ('languages', 'dum'),
    ('languages', 'dyu'),
    ('languages', 'dzo'),
    ('languages', 'frs'),
    ('languages', 'bin'),
    ('languages', 'efi'),
    ('languages', 'egy'),
    ('languages', 'eka'),
    ('languages', 'elx'),
    ('languages', 'eng'),
    ('languages', 'enm'),
    ('languages', 'ang'),
    ('languages', 'myv'),
    ('languages', 'epo'),
    ('languages', 'est'),
    ('languages', 'ewe'),
    ('languages', 'ewo'),
    ('languages', 'fan'),
    ('languages', 'fat'),
    ('languages', 'fao'),
    ('languages', 'fij'),
    ('languages', 'fil'),
    ('languages', 'fin'),
    ('languages', 'fiu'),
    ('languages', 'dut'),
    ('languages', 'fon'),
    ('languages', 'fre'),
    ('languages', 'frm'),
    ('languages', 'fro'),
    ('languages', 'fur'),
    ('languages', 'ful'),
    ('languages', 'gaa'),
    ('languages', 'gla'),
    ('languages', 'car'),
    ('languages', 'glg'),
    ('languages', 'lug'),
    ('languages', 'gay'),
    ('languages', 'gba'),
    ('languages', 'gez'),
    ('languages', 'geo'),
    ('languages', 'ger'),
    ('languages', 'nds'),
    ('languages', 'gmh'),
    ('languages', 'goh'),
    ('languages', 'gem'),
    ('languages', 'kik'),
    ('languages', 'gil'),
    ('languages', 'gon'),
    ('languages', 'gor'),
    ('languages', 'got'),
    ('languages', 'grb'),
    ('languages', 'grc'),
    ('languages', 'gre'),
    ('languages', 'kal'),
    ('languages', 'grn'),
    ('languages', 'guj'),
    ('languages', 'gwi'),
    ('languages', 'hai'),
    ('languages', 'hat'),
    ('languages', 'hat'),
    ('languages', 'hau'),
    ('languages', 'haw'),
    ('languages', 'heb'),
    ('languages', 'her'),
    ('languages', 'hil'),
    ('languages', 'him'),
    ('languages', 'hin'),
    ('languages', 'hmo'),
    ('languages', 'hit'),
    ('languages', 'hmn'),
    ('languages', 'hun'),
    ('languages', 'hup'),
    ('languages', 'iba'),
    ('languages', 'ice'),
    ('languages', 'ido'),
    ('languages', 'ibo'),
    ('languages', 'ijo'),
    ('languages', 'ilo'),
    ('languages', 'arc'),
    ('languages', 'smn'),
    ('languages', 'inc'),
    ('languages', 'ine'),
    ('languages', 'ind'),
    ('languages', 'inh'),
    ('languages', 'ina'),
    ('languages', 'ile'),
    ('languages', 'iku'),
    ('languages', 'ipk'),
    ('languages', 'ira'),
    ('languages', 'gle'),
    ('languages', 'mga'),
    ('languages', 'sga'),
    ('languages', 'iro'),
    ('languages', 'ita'),
    ('languages', 'jpn'),
    ('languages', 'jav'),
    ('languages', 'kac'),
    ('languages', 'jrb'),
    ('languages', 'jpr'),
    ('languages', 'kbd'),
    ('languages', 'kab'),
    ('languages', 'kac'),
    ('languages', 'kal'),
    ('languages', 'xal'),
    ('languages', 'kam'),
    ('languages', 'kan'),
    ('languages', 'kau'),
    ('languages', 'pam'),
    ('languages', 'kaa'),
    ('languages', 'krc'),
    ('languages', 'krl'),
    ('languages', 'kar'),
    ('languages', 'kas'),
    ('languages', 'csb'),
    ('languages', 'kaw'),
    ('languages', 'kaz'),
    ('languages', 'kha'),
    ('languages', 'khi'),
    ('languages', 'kho'),
    ('languages', 'kik'),
    ('languages', 'kmb'),
    ('languages', 'kin'),
    ('languages', 'zza'),
    ('languages', 'kir'),
    ('languages', 'zza'),
    ('languages', 'tlh'),
    ('languages', 'kom'),
    ('languages', 'kon'),
    ('languages', 'kok'),
    ('languages', 'kor'),
    ('languages', 'kos'),
    ('languages', 'kpe'),
    ('languages', 'kro'),
    ('languages', 'kua'),
    ('languages', 'kum'),
    ('languages', 'kur'),
    ('languages', 'kru'),
    ('languages', 'kut'),
    ('languages', 'kua'),
    ('languages', 'kir'),
    ('languages', 'lad'),
    ('languages', 'lah'),
    ('languages', 'lam'),
    ('languages', 'day'),
    ('languages', 'lao'),
    ('languages', 'lat'),
    ('languages', 'lav'),
    ('languages', 'ast'),
    ('languages', 'ltz'),
    ('languages', 'lez'),
    ('languages', 'lim'),
    ('languages', 'lim'),
    ('languages', 'lim'),
    ('languages', 'lin'),
    ('languages', 'lit'),
    ('languages', 'jbo'),
    ('languages', 'nds'),
    ('languages', 'nds'),
    ('languages', 'dsb'),
    ('languages', 'loz'),
    ('languages', 'lub'),
    ('languages', 'lua'),
    ('languages', 'lui'),
    ('languages', 'smj'),
    ('languages', 'lun'),
    ('languages', 'luo'),
    ('languages', 'lus'),
    ('languages', 'ltz'),
    ('languages', 'rup'),
    ('languages', 'mac'),
    ('languages', 'mad'),
    ('languages', 'mag'),
    ('languages', 'mai'),
    ('languages', 'mak'),
    ('languages', 'mlg'),
    ('languages', 'may'),
    ('languages', 'mal'),
    ('languages', 'div'),
    ('languages', 'mlt'),
    ('languages', 'mnc'),
    ('languages', 'mdr'),
    ('languages', 'man'),
    ('languages', 'mni'),
    ('languages', 'mno'),
    ('languages', 'glv'),
    ('languages', 'mao'),
    ('languages', 'arn'),
    ('languages', 'arn'),
    ('languages', 'mar'),
    ('languages', 'chm'),
    ('languages', 'mah'),
    ('languages', 'mwr'),
    ('languages', 'mas'),
    ('languages', 'myn'),
    ('languages', 'men'),
    ('languages', 'mic'),
    ('languages', 'mic'),
    ('languages', 'min'),
    ('languages', 'mwl'),
    ('languages', 'moh'),
    ('languages', 'mdf'),
    ('languages', 'rum'),
    ('languages', 'mkh'),
    ('languages', 'hmn'),
    ('languages', 'lol'),
    ('languages', 'mon'),
    ('languages', 'mot'),
    ('languages', 'mos'),
    ('languages', 'mul'),
    ('languages', 'mun'),
    ('languages', 'nqo'),
    ('languages', 'nah'),
    ('languages', 'nau'),
    ('languages', 'nav'),
    ('languages', 'nav'),
    ('languages', 'nde'),
    ('languages', 'nbl'),
    ('languages', 'ndo'),
    ('languages', 'nap'),
    ('languages', 'new'),
    ('languages', 'nep'),
    ('languages', 'new'),
    ('languages', 'nia'),
    ('languages', 'nic'),
    ('languages', 'ssa'),
    ('languages', 'niu'),
    ('languages', 'zxx'),
    ('languages', 'nog'),
    ('languages', 'non'),
    ('languages', 'nai'),
    ('languages', 'nde'),
    ('languages', 'frr'),
    ('languages', 'sme'),
    ('languages', 'nso'),
    ('languages', 'nor'),
    ('languages', 'nob'),
    ('languages', 'nno'),
    ('languages', 'zxx'),
    ('languages', 'nub'),
    ('languages', 'iii'),
    ('languages', 'nym'),
    ('languages', 'nya'),
    ('languages', 'nyn'),
    ('languages', 'nno'),
    ('languages', 'nyo'),
    ('languages', 'nzi'),
    ('languages', 'ile'),
    ('languages', 'oci'),
    ('languages', 'pro'),
    ('languages', 'arc'),
    ('languages', 'xal'),
    ('languages', 'oji'),
    ('languages', 'chu'),
    ('languages', 'chu'),
    ('languages', 'nwc'),
    ('languages', 'chu'),
    ('languages', 'ori'),
    ('languages', 'orm'),
    ('languages', 'osa'),
    ('languages', 'oss'),
    ('languages', 'oss'),
    ('languages', 'oto'),
    ('languages', 'pal'),
    ('languages', 'pau'),
    ('languages', 'pli'),
    ('languages', 'pam'),
    ('languages', 'pag'),
    ('languages', 'pan'),
    ('languages', 'pap'),
    ('languages', 'paa'),
    ('languages', 'pus'),
    ('languages', 'nso'),
    ('languages', 'per'),
    ('languages', 'peo'),
    ('languages', 'phi'),
    ('languages', 'phn'),
    ('languages', 'fil'),
    ('languages', 'pon'),
    ('languages', 'pol'),
    ('languages', 'por'),
    ('languages', 'pra'),
    ('languages', 'pro'),
    ('languages', 'pan'),
    ('languages', 'pus'),
    ('languages', 'que'),
    ('languages', 'raj'),
    ('languages', 'rap'),
    ('languages', 'rar'),
    ('languages', 'roa'),
    ('languages', 'rum'),
    ('languages', 'roh'),
    ('languages', 'rom'),
    ('languages', 'run'),
    ('languages', 'rus'),
    ('languages', 'kho'),
    ('languages', 'sal'),
    ('languages', 'sam'),
    ('languages', 'smi'),
    ('languages', 'smo'),
    ('languages', 'sad'),
    ('languages', 'sag'),
    ('languages', 'san'),
    ('languages', 'sat'),
    ('languages', 'srd'),
    ('languages', 'sas'),
    ('languages', 'nds'),
    ('languages', 'sco'),
    ('languages', 'gla'),
    ('languages', 'sel'),
    ('languages', 'sem'),
    ('languages', 'nso'),
    ('languages', 'srp'),
    ('languages', 'srr'),
    ('languages', 'shn'),
    ('languages', 'sna'),
    ('languages', 'iii'),
    ('languages', 'scn'),
    ('languages', 'sid'),
    ('languages', 'sgn'),
    ('languages', 'bla'),
    ('languages', 'snd'),
    ('languages', 'sin'),
    ('languages', 'sin'),
    ('languages', 'sit'),
    ('languages', 'sio'),
    ('languages', 'sms'),
    ('languages', 'den'),
    ('languages', 'sla'),
    ('languages', 'slo'),
    ('languages', 'slv'),
    ('languages', 'sog'),
    ('languages', 'som'),
    ('languages', 'son'),
    ('languages', 'snk'),
    ('languages', 'wen'),
    ('languages', 'nso'),
    ('languages', 'sot'),
    ('languages', 'sai'),
    ('languages', 'nbl'),
    ('languages', 'alt'),
    ('languages', 'sma'),
    ('languages', 'spa'),
    ('languages', 'srn'),
    ('languages', 'zgh'),
    ('languages', 'suk'),
    ('languages', 'sux'),
    ('languages', 'sun'),
    ('languages', 'sus'),
    ('languages', 'swa'),
    ('languages', 'ssw'),
    ('languages', 'swe'),
    ('languages', 'gsw'),
    ('languages', 'syr'),
    ('languages', 'tgl'),
    ('languages', 'tah'),
    ('languages', 'tai'),
    ('languages', 'tgk'),
    ('languages', 'tmh'),
    ('languages', 'tam'),
    ('languages', 'tat'),
    ('languages', 'tel'),
    ('languages', 'ter'),
    ('languages', 'tet'),
    ('languages', 'tha'),
    ('languages', 'tib'),
    ('languages', 'tig'),
    ('languages', 'tir'),
    ('languages', 'tem'),
    ('languages', 'tiv'),
    ('languages', 'tlh'),
    ('languages', 'tli'),
    ('languages', 'tpi'),
    ('languages', 'tkl'),
    ('languages', 'tog'),
    ('languages', 'ton'),
    ('languages', 'tsi'),
    ('languages', 'tso'),
    ('languages', 'tsn'),
    ('languages', 'tum'),
    ('languages', 'tup'),
    ('languages', 'tur'),
    ('languages', 'ota'),
    ('languages', 'tuk'),
    ('languages', 'tvl'),
    ('languages', 'tyv'),
    ('languages', 'twi'),
    ('languages', 'udm'),
    ('languages', 'uga'),
    ('languages', 'uig'),
    ('languages', 'ukr'),
    ('languages', 'umb'),
    ('languages', 'mis'),
    ('languages', 'und'),
    ('languages', 'hsb'),
    ('languages', 'urd'),
    ('languages', 'uig'),
    ('languages', 'uzb'),
    ('languages', 'vai'),
    ('languages', 'cat'),
    ('languages', 'ven'),
    ('languages', 'vie'),
    ('languages', 'vol'),
    ('languages', 'vot'),
    ('languages', 'wak'),
    ('languages', 'wln'),
    ('languages', 'war'),
    ('languages', 'was'),
    ('languages', 'wel'),
    ('languages', 'fry'),
    ('languages', 'him'),
    ('languages', 'wal'),
    ('languages', 'wal'),
    ('languages', 'wol'),
    ('languages', 'xho'),
    ('languages', 'sah'),
    ('languages', 'yao'),
    ('languages', 'yap'),
    ('languages', 'yid'),
    ('languages', 'yor'),
    ('languages', 'ypk'),
    ('languages', 'znd'),
    ('languages', 'zap'),
    ('languages', 'zza'),
    ('languages', 'zza'),
    ('languages', 'zen'),
    ('languages', 'zha'),
    ('languages', 'zul'),
    ('languages', 'zun');

INSERT INTO code_titles (category_id, code_id, locale, title) VALUES
    ('countries', 'AF', 'en', 'Afghanistan'),
    ('countries', 'AX', 'en', 'Aland Islands'),
    ('countries', 'AL', 'en', 'Albania'),
    ('countries', 'DZ', 'en', 'Algeria'),
    ('countries', 'AS', 'en', 'American Samoa'),
    ('countries', 'AD', 'en', 'Andorra'),
    ('countries', 'AO', 'en', 'Angola'),
    ('countries', 'AI', 'en', 'Anguilla'),
    ('countries', 'AQ', 'en', 'Antarctica'),
    ('countries', 'AG', 'en', 'Antigua and Barbuda'),
    ('countries', 'AR', 'en', 'Argentina'),
    ('countries', 'AM', 'en', 'Armenia'),
    ('countries', 'AW', 'en', 'Aruba'),
    ('countries', 'AU', 'en', 'Australia'),
    ('countries', 'AT', 'en', 'Austria'),
    ('countries', 'AZ', 'en', 'Azerbaijan'),
    ('countries', 'BS', 'en', 'Bahamas'),
    ('countries', 'BH', 'en', 'Bahrain'),
    ('countries', 'BD', 'en', 'Bangladesh'),
    ('countries', 'BB', 'en', 'Barbados'),
    ('countries', 'BY', 'en', 'Belarus'),
    ('countries', 'BE', 'en', 'Belgium'),
    ('countries', 'BZ', 'en', 'Belize'),
    ('countries', 'BJ', 'en', 'Benin'),
    ('countries', 'BM', 'en', 'Bermuda'),
    ('countries', 'BT', 'en', 'Bhutan'),
    ('countries', 'BO', 'en', 'Bolivia'),
    ('countries', 'BA', 'en', 'Bosnia and Herzegovina'),
    ('countries', 'BW', 'en', 'Botswana'),
    ('countries', 'BV', 'en', 'Bouvet Island'),
    ('countries', 'BR', 'en', 'Brazil'),
    ('countries', 'VG', 'en', 'British Virgin Islands'),
    ('countries', 'IO', 'en', 'British Indian Ocean Territory'),
    ('countries', 'BN', 'en', 'Brunei Darussalam'),
    ('countries', 'BG', 'en', 'Bulgaria'),
    ('countries', 'BF', 'en', 'Burkina Faso'),
    ('countries', 'BI', 'en', 'Burundi'),
    ('countries', 'KH', 'en', 'Cambodia'),
    ('countries', 'CM', 'en', 'Cameroon'),
    ('countries', 'CA', 'en', 'Canada'),
    ('countries', 'CV', 'en', 'Cape Verde'),
    ('countries', 'KY', 'en', 'Cayman Islands'),
    ('countries', 'CF', 'en', 'Central African Republic'),
    ('countries', 'TD', 'en', 'Chad'),
    ('countries', 'CL', 'en', 'Chile'),
    ('countries', 'CN', 'en', 'China'),
    ('countries', 'HK', 'en', 'Hong Kong, SAR China'),
    ('countries', 'MO', 'en', 'Macao, SAR China'),
    ('countries', 'CX', 'en', 'Christmas Island'),
    ('countries', 'CC', 'en', 'Cocos (Keeling) Islands'),
    ('countries', 'CO', 'en', 'Colombia'),
    ('countries', 'KM', 'en', 'Comoros'),
    ('countries', 'CG', 'en', 'Congo (Brazzaville)'),
    ('countries', 'CD', 'en', 'Congo, (Kinshasa)'),
    ('countries', 'CK', 'en', 'Cook Islands'),
    ('countries', 'CR', 'en', 'Costa Rica'),
    ('countries', 'CI', 'en', 'Côte d''Ivoire'),
    ('countries', 'HR', 'en', 'Croatia'),
    ('countries', 'CU', 'en', 'Cuba'),
    ('countries', 'CY', 'en', 'Cyprus'),
    ('countries', 'CZ', 'en', 'Czech Republic'),
    ('countries', 'DK', 'en', 'Denmark'),
    ('countries', 'DJ', 'en', 'Djibouti'),
    ('countries', 'DM', 'en', 'Dominica'),
    ('countries', 'DO', 'en', 'Dominican Republic'),
    ('countries', 'EC', 'en', 'Ecuador'),
    ('countries', 'EG', 'en', 'Egypt'),
    ('countries', 'SV', 'en', 'El Salvador'),
    ('countries', 'GQ', 'en', 'Equatorial Guinea'),
    ('countries', 'ER', 'en', 'Eritrea'),
    ('countries', 'EE', 'en', 'Estonia'),
    ('countries', 'ET', 'en', 'Ethiopia'),
    ('countries', 'FK', 'en', 'Falkland Islands (Malvinas)'),
    ('countries', 'FO', 'en', 'Faroe Islands'),
    ('countries', 'FJ', 'en', 'Fiji'),
    ('countries', 'FI', 'en', 'Finland'),
    ('countries', 'FR', 'en', 'France'),
    ('countries', 'GF', 'en', 'French Guiana'),
    ('countries', 'PF', 'en', 'French Polynesia'),
    ('countries', 'TF', 'en', 'French Southern Territories'),
    ('countries', 'GA', 'en', 'Gabon'),
    ('countries', 'GM', 'en', 'Gambia'),
    ('countries', 'GE', 'en', 'Georgia'),
    ('countries', 'DE', 'en', 'Germany'),
    ('countries', 'GH', 'en', 'Ghana'),
    ('countries', 'GI', 'en', 'Gibraltar'),
    ('countries', 'GR', 'en', 'Greece'),
    ('countries', 'GL', 'en', 'Greenland'),
    ('countries', 'GD', 'en', 'Grenada'),
    ('countries', 'GP', 'en', 'Guadeloupe'),
    ('countries', 'GU', 'en', 'Guam'),
    ('countries', 'GT', 'en', 'Guatemala'),
    ('countries', 'GG', 'en', 'Guernsey'),
    ('countries', 'GN', 'en', 'Guinea'),
    ('countries', 'GW', 'en', 'Guinea-Bissau'),
    ('countries', 'GY', 'en', 'Guyana'),
    ('countries', 'HT', 'en', 'Haiti'),
    ('countries', 'HM', 'en', 'Heard and Mcdonald Islands'),
    ('countries', 'VA', 'en', 'Holy See (Vatican City State)'),
    ('countries', 'HN', 'en', 'Honduras'),
    ('countries', 'HU', 'en', 'Hungary'),
    ('countries', 'IS', 'en', 'Iceland'),
    ('countries', 'IN', 'en', 'India'),
    ('countries', 'ID', 'en', 'Indonesia'),
    ('countries', 'IR', 'en', 'Iran, Islamic Republic of'),
    ('countries', 'IQ', 'en', 'Iraq'),
    ('countries', 'IE', 'en', 'Ireland'),
    ('countries', 'IM', 'en', 'Isle of Man'),
    ('countries', 'IL', 'en', 'Israel'),
    ('countries', 'IT', 'en', 'Italy'),
    ('countries', 'JM', 'en', 'Jamaica'),
    ('countries', 'JP', 'en', 'Japan'),
    ('countries', 'JE', 'en', 'Jersey'),
    ('countries', 'JO', 'en', 'Jordan'),
    ('countries', 'KZ', 'en', 'Kazakhstan'),
    ('countries', 'KE', 'en', 'Kenya'),
    ('countries', 'KI', 'en', 'Kiribati'),
    ('countries', 'KP', 'en', 'Korea (North)'),
    ('countries', 'KR', 'en', 'Korea (South)'),
    ('countries', 'KW', 'en', 'Kuwait'),
    ('countries', 'KG', 'en', 'Kyrgyzstan'),
    ('countries', 'LA', 'en', 'Lao PDR'),
    ('countries', 'LV', 'en', 'Latvia'),
    ('countries', 'LB', 'en', 'Lebanon'),
    ('countries', 'LS', 'en', 'Lesotho'),
    ('countries', 'LR', 'en', 'Liberia'),
    ('countries', 'LY', 'en', 'Libya'),
    ('countries', 'LI', 'en', 'Liechtenstein'),
    ('countries', 'LT', 'en', 'Lithuania'),
    ('countries', 'LU', 'en', 'Luxembourg'),
    ('countries', 'MK', 'en', 'Macedonia, Republic of'),
    ('countries', 'MG', 'en', 'Madagascar'),
    ('countries', 'MW', 'en', 'Malawi'),
    ('countries', 'MY', 'en', 'Malaysia'),
    ('countries', 'MV', 'en', 'Maldives'),
    ('countries', 'ML', 'en', 'Mali'),
    ('countries', 'MT', 'en', 'Malta'),
    ('countries', 'MH', 'en', 'Marshall Islands'),
    ('countries', 'MQ', 'en', 'Martinique'),
    ('countries', 'MR', 'en', 'Mauritania'),
    ('countries', 'MU', 'en', 'Mauritius'),
    ('countries', 'YT', 'en', 'Mayotte'),
    ('countries', 'MX', 'en', 'Mexico'),
    ('countries', 'FM', 'en', 'Micronesia, Federated States of'),
    ('countries', 'MD', 'en', 'Moldova'),
    ('countries', 'MC', 'en', 'Monaco'),
    ('countries', 'MN', 'en', 'Mongolia'),
    ('countries', 'ME', 'en', 'Montenegro'),
    ('countries', 'MS', 'en', 'Montserrat'),
    ('countries', 'MA', 'en', 'Morocco'),
    ('countries', 'MZ', 'en', 'Mozambique'),
    ('countries', 'MM', 'en', 'Myanmar'),
    ('countries', 'NA', 'en', 'Namibia'),
    ('countries', 'NR', 'en', 'Nauru'),
    ('countries', 'NP', 'en', 'Nepal'),
    ('countries', 'NL', 'en', 'Netherlands'),
    ('countries', 'AN', 'en', 'Netherlands Antilles'),
    ('countries', 'NC', 'en', 'New Caledonia'),
    ('countries', 'NZ', 'en', 'New Zealand'),
    ('countries', 'NI', 'en', 'Nicaragua'),
    ('countries', 'NE', 'en', 'Niger'),
    ('countries', 'NG', 'en', 'Nigeria'),
    ('countries', 'NU', 'en', 'Niue'),
    ('countries', 'NF', 'en', 'Norfolk Island'),
    ('countries', 'MP', 'en', 'Northern Mariana Islands'),
    ('countries', 'NO', 'en', 'Norway'),
    ('countries', 'OM', 'en', 'Oman'),
    ('countries', 'PK', 'en', 'Pakistan'),
    ('countries', 'PW', 'en', 'Palau'),
    ('countries', 'PS', 'en', 'Palestinian Territory'),
    ('countries', 'PA', 'en', 'Panama'),
    ('countries', 'PG', 'en', 'Papua New Guinea'),
    ('countries', 'PY', 'en', 'Paraguay'),
    ('countries', 'PE', 'en', 'Peru'),
    ('countries', 'PH', 'en', 'Philippines'),
    ('countries', 'PN', 'en', 'Pitcairn'),
    ('countries', 'PL', 'en', 'Poland'),
    ('countries', 'PT', 'en', 'Portugal'),
    ('countries', 'PR', 'en', 'Puerto Rico'),
    ('countries', 'QA', 'en', 'Qatar'),
    ('countries', 'RE', 'en', 'Réunion'),
    ('countries', 'RO', 'en', 'Romania'),
    ('countries', 'RU', 'en', 'Russian Federation'),
    ('countries', 'RW', 'en', 'Rwanda'),
    ('countries', 'BL', 'en', 'Saint-Barthélemy'),
    ('countries', 'SH', 'en', 'Saint Helena'),
    ('countries', 'KN', 'en', 'Saint Kitts and Nevis'),
    ('countries', 'LC', 'en', 'Saint Lucia'),
    ('countries', 'MF', 'en', 'Saint-Martin (French part)'),
    ('countries', 'PM', 'en', 'Saint Pierre and Miquelon'),
    ('countries', 'VC', 'en', 'Saint Vincent and Grenadines'),
    ('countries', 'WS', 'en', 'Samoa'),
    ('countries', 'SM', 'en', 'San Marino'),
    ('countries', 'ST', 'en', 'Sao Tome and Principe'),
    ('countries', 'SA', 'en', 'Saudi Arabia'),
    ('countries', 'SN', 'en', 'Senegal'),
    ('countries', 'RS', 'en', 'Serbia'),
    ('countries', 'SC', 'en', 'Seychelles'),
    ('countries', 'SL', 'en', 'Sierra Leone'),
    ('countries', 'SG', 'en', 'Singapore'),
    ('countries', 'SK', 'en', 'Slovakia'),
    ('countries', 'SI', 'en', 'Slovenia'),
    ('countries', 'SB', 'en', 'Solomon Islands'),
    ('countries', 'SO', 'en', 'Somalia'),
    ('countries', 'ZA', 'en', 'South Africa'),
    ('countries', 'GS', 'en', 'South Georgia and the South Sandwich Islands'),
    ('countries', 'SS', 'en', 'South Sudan'),
    ('countries', 'ES', 'en', 'Spain'),
    ('countries', 'LK', 'en', 'Sri Lanka'),
    ('countries', 'SD', 'en', 'Sudan'),
    ('countries', 'SR', 'en', 'Suriname'),
    ('countries', 'SJ', 'en', 'Svalbard and Jan Mayen Islands'),
    ('countries', 'SZ', 'en', 'Swaziland'),
    ('countries', 'SE', 'en', 'Sweden'),
    ('countries', 'CH', 'en', 'Switzerland'),
    ('countries', 'SY', 'en', 'Syrian Arab Republic (Syria)'),
    ('countries', 'TW', 'en', 'Taiwan, Republic of China'),
    ('countries', 'TJ', 'en', 'Tajikistan'),
    ('countries', 'TZ', 'en', 'Tanzania, United Republic of'),
    ('countries', 'TH', 'en', 'Thailand'),
    ('countries', 'TL', 'en', 'Timor-Leste'),
    ('countries', 'TG', 'en', 'Togo'),
    ('countries', 'TK', 'en', 'Tokelau'),
    ('countries', 'TO', 'en', 'Tonga'),
    ('countries', 'TT', 'en', 'Trinidad and Tobago'),
    ('countries', 'TN', 'en', 'Tunisia'),
    ('countries', 'TR', 'en', 'Turkey'),
    ('countries', 'TM', 'en', 'Turkmenistan'),
    ('countries', 'TC', 'en', 'Turks and Caicos Islands'),
    ('countries', 'TV', 'en', 'Tuvalu'),
    ('countries', 'UG', 'en', 'Uganda'),
    ('countries', 'UA', 'en', 'Ukraine'),
    ('countries', 'AE', 'en', 'United Arab Emirates'),
    ('countries', 'GB', 'en', 'United Kingdom'),
    ('countries', 'US', 'en', 'United States of America'),
    ('countries', 'UM', 'en', 'US Minor Outlying Islands'),
    ('countries', 'UY', 'en', 'Uruguay'),
    ('countries', 'UZ', 'en', 'Uzbekistan'),
    ('countries', 'VU', 'en', 'Vanuatu'),
    ('countries', 'VE', 'en', 'Venezuela (Bolivarian Republic)'),
    ('countries', 'VN', 'en', 'Viet Nam'),
    ('countries', 'VI', 'en', 'Virgin Islands, US'),
    ('countries', 'WF', 'en', 'Wallis and Futuna Islands'),
    ('countries', 'EH', 'en', 'Western Sahara'),
    ('countries', 'YE', 'en', 'Yemen'),
    ('countries', 'ZM', 'en', 'Zambia'),
    ('countries', 'ZW', 'en', 'Zimbabwe'),

    ('languages', 'abk', 'en', 'Abkhazian'),
    ('languages', 'ace', 'en', 'Achinese'),
    ('languages', 'ach', 'en', 'Acoli'),
    ('languages', 'ada', 'en', 'Adangme'),
    ('languages', 'ady', 'en', 'Adygei'),
    ('languages', 'ady', 'en', 'Adyghe'),
    ('languages', 'aar', 'en', 'Afar'),
    ('languages', 'afh', 'en', 'Afrihili'),
    ('languages', 'afr', 'en', 'Afrikaans'),
    ('languages', 'afa', 'en', 'Afro-Asiatic languages'),
    ('languages', 'ain', 'en', 'Ainu'),
    ('languages', 'aka', 'en', 'Akan'),
    ('languages', 'akk', 'en', 'Akkadian'),
    ('languages', 'alb', 'en', 'Albanian","sq'),
    ('languages', 'gsw', 'en', 'Alemannic'),
    ('languages', 'ale', 'en', 'Aleut'),
    ('languages', 'alg', 'en', 'Algonquian languages'),
    ('languages', 'gsw', 'en', 'Alsatian'),
    ('languages', 'tut', 'en', 'Altaic languages'),
    ('languages', 'amh', 'en', 'Amharic'),
    ('languages', 'anp', 'en', 'Angika'),
    ('languages', 'apa', 'en', 'Apache languages'),
    ('languages', 'ara', 'en', 'Arabic'),
    ('languages', 'arg', 'en', 'Aragonese'),
    ('languages', 'arp', 'en', 'Arapaho'),
    ('languages', 'arw', 'en', 'Arawak'),
    ('languages', 'arm', 'en', 'Armenian","hy'),
    ('languages', 'rup', 'en', 'Aromanian'),
    ('languages', 'art', 'en', 'Artificial languages'),
    ('languages', 'rup', 'en', 'Arumanian'),
    ('languages', 'asm', 'en', 'Assamese'),
    ('languages', 'ast', 'en', 'Asturian'),
    ('languages', 'ast', 'en', 'Asturleonese'),
    ('languages', 'ath', 'en', 'Athapascan languages'),
    ('languages', 'aus', 'en', 'Australian languages'),
    ('languages', 'map', 'en', 'Austronesian languages'),
    ('languages', 'ava', 'en', 'Avaric'),
    ('languages', 'ave', 'en', 'Avestan'),
    ('languages', 'awa', 'en', 'Awadhi'),
    ('languages', 'aym', 'en', 'Aymara'),
    ('languages', 'aze', 'en', 'Azerbaijani'),
    ('languages', 'ast', 'en', 'Bable'),
    ('languages', 'ban', 'en', 'Balinese'),
    ('languages', 'bat', 'en', 'Baltic languages'),
    ('languages', 'bal', 'en', 'Baluchi'),
    ('languages', 'bam', 'en', 'Bambara'),
    ('languages', 'bai', 'en', 'Bamileke languages'),
    ('languages', 'bad', 'en', 'Banda languages'),
    ('languages', 'bnt', 'en', 'Bantu languages'),
    ('languages', 'bas', 'en', 'Basa'),
    ('languages', 'bak', 'en', 'Bashkir'),
    ('languages', 'baq', 'en', 'Basque","eu'),
    ('languages', 'btk', 'en', 'Batak languages'),
    ('languages', 'bej', 'en', 'Bedawiyet'),
    ('languages', 'bej', 'en', 'Beja'),
    ('languages', 'bel', 'en', 'Belarusian'),
    ('languages', 'bem', 'en', 'Bemba'),
    ('languages', 'ben', 'en', 'Bengali'),
    ('languages', 'ber', 'en', 'Berber languages'),
    ('languages', 'bho', 'en', 'Bhojpuri'),
    ('languages', 'bih', 'en', 'Bihari languages'),
    ('languages', 'bik', 'en', 'Bikol'),
    ('languages', 'byn', 'en', 'Bilin'),
    ('languages', 'bin', 'en', 'Bini'),
    ('languages', 'bis', 'en', 'Bislama'),
    ('languages', 'byn', 'en', 'Blin'),
    ('languages', 'zbl', 'en', 'Bliss'),
    ('languages', 'zbl', 'en', 'Blissymbolics'),
    ('languages', 'zbl', 'en', 'Blissymbols'),
    ('languages', 'nob', 'en', 'Bokmål, Norwegian'),
    ('languages', 'bos', 'en', 'Bosnian'),
    ('languages', 'bra', 'en', 'Braj'),
    ('languages', 'bre', 'en', 'Breton'),
    ('languages', 'bug', 'en', 'Buginese'),
    ('languages', 'bul', 'en', 'Bulgarian'),
    ('languages', 'bua', 'en', 'Buriat'),
    ('languages', 'bur', 'en', 'Burmese","my'),
    ('languages', 'cad', 'en', 'Caddo'),
    ('languages', 'spa', 'en', 'Castilian'),
    ('languages', 'cat', 'en', 'Catalan'),
    ('languages', 'cau', 'en', 'Caucasian languages'),
    ('languages', 'ceb', 'en', 'Cebuano'),
    ('languages', 'cel', 'en', 'Celtic languages'),
    ('languages', 'cai', 'en', 'Central American Indian languages'),
    ('languages', 'khm', 'en', 'Central Khmer'),
    ('languages', 'chg', 'en', 'Chagatai'),
    ('languages', 'cmc', 'en', 'Chamic languages'),
    ('languages', 'cha', 'en', 'Chamorro'),
    ('languages', 'che', 'en', 'Chechen'),
    ('languages', 'chr', 'en', 'Cherokee'),
    ('languages', 'nya', 'en', 'Chewa'),
    ('languages', 'chy', 'en', 'Cheyenne'),
    ('languages', 'chb', 'en', 'Chibcha'),
    ('languages', 'nya', 'en', 'Chichewa'),
    ('languages', 'chi', 'en', 'Chinese","zh'),
    ('languages', 'chn', 'en', 'Chinook jargon'),
    ('languages', 'chp', 'en', 'Chipewyan'),
    ('languages', 'cho', 'en', 'Choctaw'),
    ('languages', 'zha', 'en', 'Chuang'),
    ('languages', 'chu', 'en', 'Church Slavic'),
    ('languages', 'chu', 'en', 'Church Slavonic'),
    ('languages', 'chk', 'en', 'Chuukese'),
    ('languages', 'chv', 'en', 'Chuvash'),
    ('languages', 'nwc', 'en', 'Classical Nepal Bhasa'),
    ('languages', 'nwc', 'en', 'Classical Newari'),
    ('languages', 'syc', 'en', 'Classical Syriac'),
    ('languages', 'rar', 'en', 'Cook Islands Maori'),
    ('languages', 'cop', 'en', 'Coptic'),
    ('languages', 'cor', 'en', 'Cornish'),
    ('languages', 'cos', 'en', 'Corsican'),
    ('languages', 'cre', 'en', 'Cree'),
    ('languages', 'mus', 'en', 'Creek'),
    ('languages', 'crp', 'en', 'Creoles and pidgins'),
    ('languages', 'cpe', 'en', 'Creoles and pidgins, English based'),
    ('languages', 'cpf', 'en', 'Creoles and pidgins, French-based'),
    ('languages', 'cpp', 'en', 'Creoles and pidgins, Portuguese-based'),
    ('languages', 'crh', 'en', 'Crimean Tatar'),
    ('languages', 'crh', 'en', 'Crimean Turkish'),
    ('languages', 'hrv', 'en', 'Croatian'),
    ('languages', 'cus', 'en', 'Cushitic languages'),
    ('languages', 'cze', 'en', 'Czech","cs'),
    ('languages', 'dak', 'en', 'Dakota'),
    ('languages', 'dan', 'en', 'Danish'),
    ('languages', 'dar', 'en', 'Dargwa'),
    ('languages', 'del', 'en', 'Delaware'),
    ('languages', 'chp', 'en', 'Dene Suline'),
    ('languages', 'div', 'en', 'Dhivehi'),
    ('languages', 'zza', 'en', 'Dimili'),
    ('languages', 'zza', 'en', 'Dimli'),
    ('languages', 'din', 'en', 'Dinka'),
    ('languages', 'div', 'en', 'Divehi'),
    ('languages', 'doi', 'en', 'Dogri'),
    ('languages', 'dgr', 'en', 'Dogrib'),
    ('languages', 'dra', 'en', 'Dravidian languages'),
    ('languages', 'dua', 'en', 'Duala'),
    ('languages', 'dut', 'en', 'Dutch","nl'),
    ('languages', 'dum', 'en', 'Dutch, Middle (ca.1050-1350)'),
    ('languages', 'dyu', 'en', 'Dyula'),
    ('languages', 'dzo', 'en', 'Dzongkha'),
    ('languages', 'frs', 'en', 'Eastern Frisian'),
    ('languages', 'bin', 'en', 'Edo'),
    ('languages', 'efi', 'en', 'Efik'),
    ('languages', 'egy', 'en', 'Egyptian (Ancient)'),
    ('languages', 'eka', 'en', 'Ekajuk'),
    ('languages', 'elx', 'en', 'Elamite'),
    ('languages', 'eng', 'en', 'English'),
    ('languages', 'enm', 'en', 'English, Middle (1100-1500)'),
    ('languages', 'ang', 'en', 'English, Old (ca.450-1100)'),
    ('languages', 'myv', 'en', 'Erzya'),
    ('languages', 'epo', 'en', 'Esperanto'),
    ('languages', 'est', 'en', 'Estonian'),
    ('languages', 'ewe', 'en', 'Ewe'),
    ('languages', 'ewo', 'en', 'Ewondo'),
    ('languages', 'fan', 'en', 'Fang'),
    ('languages', 'fat', 'en', 'Fanti'),
    ('languages', 'fao', 'en', 'Faroese'),
    ('languages', 'fij', 'en', 'Fijian'),
    ('languages', 'fil', 'en', 'Filipino'),
    ('languages', 'fin', 'en', 'Finnish'),
    ('languages', 'fiu', 'en', 'Finno-Ugrian languages'),
    ('languages', 'dut', 'en', 'Flemish","nl'),
    ('languages', 'fon', 'en', 'Fon'),
    ('languages', 'fre', 'en', 'French","fr'),
    ('languages', 'frm', 'en', 'French, Middle (ca.1400-1600)'),
    ('languages', 'fro', 'en', 'French, Old (842-ca.1400)'),
    ('languages', 'fur', 'en', 'Friulian'),
    ('languages', 'ful', 'en', 'Fulah'),
    ('languages', 'gaa', 'en', 'Ga'),
    ('languages', 'gla', 'en', 'Gaelic'),
    ('languages', 'car', 'en', 'Galibi Carib'),
    ('languages', 'glg', 'en', 'Galician'),
    ('languages', 'lug', 'en', 'Ganda'),
    ('languages', 'gay', 'en', 'Gayo'),
    ('languages', 'gba', 'en', 'Gbaya'),
    ('languages', 'gez', 'en', 'Geez'),
    ('languages', 'geo', 'en', 'Georgian","ka'),
    ('languages', 'ger', 'en', 'German","de'),
    ('languages', 'nds', 'en', 'German, Low'),
    ('languages', 'gmh', 'en', 'German, Middle High (ca.1050-1500)'),
    ('languages', 'goh', 'en', 'German, Old High (ca.750-1050)'),
    ('languages', 'gem', 'en', 'Germanic languages'),
    ('languages', 'kik', 'en', 'Gikuyu'),
    ('languages', 'gil', 'en', 'Gilbertese'),
    ('languages', 'gon', 'en', 'Gondi'),
    ('languages', 'gor', 'en', 'Gorontalo'),
    ('languages', 'got', 'en', 'Gothic'),
    ('languages', 'grb', 'en', 'Grebo'),
    ('languages', 'grc', 'en', 'Greek, Ancient (to 1453)'),
    ('languages', 'gre', 'en', 'Greek, Modern (1453-)","el'),
    ('languages', 'kal', 'en', 'Greenlandic'),
    ('languages', 'grn', 'en', 'Guarani'),
    ('languages', 'guj', 'en', 'Gujarati'),
    ('languages', 'gwi', 'en', 'Gwich''in'),
    ('languages', 'hai', 'en', 'Haida'),
    ('languages', 'hat', 'en', 'Haitian'),
    ('languages', 'hat', 'en', 'Haitian Creole'),
    ('languages', 'hau', 'en', 'Hausa'),
    ('languages', 'haw', 'en', 'Hawaiian'),
    ('languages', 'heb', 'en', 'Hebrew'),
    ('languages', 'her', 'en', 'Herero'),
    ('languages', 'hil', 'en', 'Hiligaynon'),
    ('languages', 'him', 'en', 'Himachali languages'),
    ('languages', 'hin', 'en', 'Hindi'),
    ('languages', 'hmo', 'en', 'Hiri Motu'),
    ('languages', 'hit', 'en', 'Hittite'),
    ('languages', 'hmn', 'en', 'Hmong'),
    ('languages', 'hun', 'en', 'Hungarian'),
    ('languages', 'hup', 'en', 'Hupa'),
    ('languages', 'iba', 'en', 'Iban'),
    ('languages', 'ice', 'en', 'Icelandic","is'),
    ('languages', 'ido', 'en', 'Ido'),
    ('languages', 'ibo', 'en', 'Igbo'),
    ('languages', 'ijo', 'en', 'Ijo languages'),
    ('languages', 'ilo', 'en', 'Iloko'),
    ('languages', 'arc', 'en', 'Imperial Aramaic (700-300 BCE)'),
    ('languages', 'smn', 'en', 'Inari Sami'),
    ('languages', 'inc', 'en', 'Indic languages'),
    ('languages', 'ine', 'en', 'Indo-European languages'),
    ('languages', 'ind', 'en', 'Indonesian'),
    ('languages', 'inh', 'en', 'Ingush'),
    ('languages', 'ina', 'en', 'Interlingua (International Auxiliary Language Association)'),
    ('languages', 'ile', 'en', 'Interlingue'),
    ('languages', 'iku', 'en', 'Inuktitut'),
    ('languages', 'ipk', 'en', 'Inupiaq'),
    ('languages', 'ira', 'en', 'Iranian languages'),
    ('languages', 'gle', 'en', 'Irish'),
    ('languages', 'mga', 'en', 'Irish, Middle (900-1200)'),
    ('languages', 'sga', 'en', 'Irish, Old (to 900)'),
    ('languages', 'iro', 'en', 'Iroquoian languages'),
    ('languages', 'ita', 'en', 'Italian'),
    ('languages', 'jpn', 'en', 'Japanese'),
    ('languages', 'jav', 'en', 'Javanese'),
    ('languages', 'kac', 'en', 'Jingpho'),
    ('languages', 'jrb', 'en', 'Judeo-Arabic'),
    ('languages', 'jpr', 'en', 'Judeo-Persian'),
    ('languages', 'kbd', 'en', 'Kabardian'),
    ('languages', 'kab', 'en', 'Kabyle'),
    ('languages', 'kac', 'en', 'Kachin'),
    ('languages', 'kal', 'en', 'Kalaallisut'),
    ('languages', 'xal', 'en', 'Kalmyk'),
    ('languages', 'kam', 'en', 'Kamba'),
    ('languages', 'kan', 'en', 'Kannada'),
    ('languages', 'kau', 'en', 'Kanuri'),
    ('languages', 'pam', 'en', 'Kapampangan'),
    ('languages', 'kaa', 'en', 'Kara-Kalpak'),
    ('languages', 'krc', 'en', 'Karachay-Balkar'),
    ('languages', 'krl', 'en', 'Karelian'),
    ('languages', 'kar', 'en', 'Karen languages'),
    ('languages', 'kas', 'en', 'Kashmiri'),
    ('languages', 'csb', 'en', 'Kashubian'),
    ('languages', 'kaw', 'en', 'Kawi'),
    ('languages', 'kaz', 'en', 'Kazakh'),
    ('languages', 'kha', 'en', 'Khasi'),
    ('languages', 'khi', 'en', 'Khoisan languages'),
    ('languages', 'kho', 'en', 'Khotanese'),
    ('languages', 'kik', 'en', 'Kikuyu'),
    ('languages', 'kmb', 'en', 'Kimbundu'),
    ('languages', 'kin', 'en', 'Kinyarwanda'),
    ('languages', 'zza', 'en', 'Kirdki'),
    ('languages', 'kir', 'en', 'Kirghiz'),
    ('languages', 'zza', 'en', 'Kirmanjki'),
    ('languages', 'tlh', 'en', 'Klingon'),
    ('languages', 'kom', 'en', 'Komi'),
    ('languages', 'kon', 'en', 'Kongo'),
    ('languages', 'kok', 'en', 'Konkani'),
    ('languages', 'kor', 'en', 'Korean'),
    ('languages', 'kos', 'en', 'Kosraean'),
    ('languages', 'kpe', 'en', 'Kpelle'),
    ('languages', 'kro', 'en', 'Kru languages'),
    ('languages', 'kua', 'en', 'Kuanyama'),
    ('languages', 'kum', 'en', 'Kumyk'),
    ('languages', 'kur', 'en', 'Kurdish'),
    ('languages', 'kru', 'en', 'Kurukh'),
    ('languages', 'kut', 'en', 'Kutenai'),
    ('languages', 'kua', 'en', 'Kwanyama'),
    ('languages', 'kir', 'en', 'Kyrgyz'),
    ('languages', 'lad', 'en', 'Ladino'),
    ('languages', 'lah', 'en', 'Lahnda'),
    ('languages', 'lam', 'en', 'Lamba'),
    ('languages', 'day', 'en', 'Land Dayak languages'),
    ('languages', 'lao', 'en', 'Lao'),
    ('languages', 'lat', 'en', 'Latin'),
    ('languages', 'lav', 'en', 'Latvian'),
    ('languages', 'ast', 'en', 'Leonese'),
    ('languages', 'ltz', 'en', 'Letzeburgesch'),
    ('languages', 'lez', 'en', 'Lezghian'),
    ('languages', 'lim', 'en', 'Limburgan'),
    ('languages', 'lim', 'en', 'Limburger'),
    ('languages', 'lim', 'en', 'Limburgish'),
    ('languages', 'lin', 'en', 'Lingala'),
    ('languages', 'lit', 'en', 'Lithuanian'),
    ('languages', 'jbo', 'en', 'Lojban'),
    ('languages', 'nds', 'en', 'Low German'),
    ('languages', 'nds', 'en', 'Low Saxon'),
    ('languages', 'dsb', 'en', 'Lower Sorbian'),
    ('languages', 'loz', 'en', 'Lozi'),
    ('languages', 'lub', 'en', 'Luba-Katanga'),
    ('languages', 'lua', 'en', 'Luba-Lulua'),
    ('languages', 'lui', 'en', 'Luiseno'),
    ('languages', 'smj', 'en', 'Lule Sami'),
    ('languages', 'lun', 'en', 'Lunda'),
    ('languages', 'luo', 'en', 'Luo (Kenya and Tanzania)'),
    ('languages', 'lus', 'en', 'Lushai'),
    ('languages', 'ltz', 'en', 'Luxembourgish'),
    ('languages', 'rup', 'en', 'Macedo-Romanian'),
    ('languages', 'mac', 'en', 'Macedonian","mk'),
    ('languages', 'mad', 'en', 'Madurese'),
    ('languages', 'mag', 'en', 'Magahi'),
    ('languages', 'mai', 'en', 'Maithili'),
    ('languages', 'mak', 'en', 'Makasar'),
    ('languages', 'mlg', 'en', 'Malagasy'),
    ('languages', 'may', 'en', 'Malay","ms'),
    ('languages', 'mal', 'en', 'Malayalam'),
    ('languages', 'div', 'en', 'Maldivian'),
    ('languages', 'mlt', 'en', 'Maltese'),
    ('languages', 'mnc', 'en', 'Manchu'),
    ('languages', 'mdr', 'en', 'Mandar'),
    ('languages', 'man', 'en', 'Mandingo'),
    ('languages', 'mni', 'en', 'Manipuri'),
    ('languages', 'mno', 'en', 'Manobo languages'),
    ('languages', 'glv', 'en', 'Manx'),
    ('languages', 'mao', 'en', 'Maori","mi'),
    ('languages', 'arn', 'en', 'Mapuche'),
    ('languages', 'arn', 'en', 'Mapudungun'),
    ('languages', 'mar', 'en', 'Marathi'),
    ('languages', 'chm', 'en', 'Mari'),
    ('languages', 'mah', 'en', 'Marshallese'),
    ('languages', 'mwr', 'en', 'Marwari'),
    ('languages', 'mas', 'en', 'Masai'),
    ('languages', 'myn', 'en', 'Mayan languages'),
    ('languages', 'men', 'en', 'Mende'),
    ('languages', 'mic', 'en', 'Mi''kmaq'),
    ('languages', 'mic', 'en', 'Micmac'),
    ('languages', 'min', 'en', 'Minangkabau'),
    ('languages', 'mwl', 'en', 'Mirandese'),
    ('languages', 'moh', 'en', 'Mohawk'),
    ('languages', 'mdf', 'en', 'Moksha'),
    ('languages', 'rum', 'en', 'Moldavian","ro'),
    ('languages', 'mkh', 'en', 'Mon-Khmer languages'),
    ('languages', 'hmn', 'en', 'Mong'),
    ('languages', 'lol', 'en', 'Mongo'),
    ('languages', 'mon', 'en', 'Mongolian'),
    ('languages', 'mot', 'en', 'Montenegrin'),
    ('languages', 'mos', 'en', 'Mossi'),
    ('languages', 'mul', 'en', 'Multiple languages'),
    ('languages', 'mun', 'en', 'Munda languages'),
    ('languages', 'nqo', 'en', 'N''Ko'),
    ('languages', 'nah', 'en', 'Nahuatl languages'),
    ('languages', 'nau', 'en', 'Nauru'),
    ('languages', 'nav', 'en', 'Navaho'),
    ('languages', 'nav', 'en', 'Navajo'),
    ('languages', 'nde', 'en', 'Ndebele, North'),
    ('languages', 'nbl', 'en', 'Ndebele, South'),
    ('languages', 'ndo', 'en', 'Ndonga'),
    ('languages', 'nap', 'en', 'Neapolitan'),
    ('languages', 'new', 'en', 'Nepal Bhasa'),
    ('languages', 'nep', 'en', 'Nepali'),
    ('languages', 'new', 'en', 'Newari'),
    ('languages', 'nia', 'en', 'Nias'),
    ('languages', 'nic', 'en', 'Niger-Kordofanian languages'),
    ('languages', 'ssa', 'en', 'Nilo-Saharan languages'),
    ('languages', 'niu', 'en', 'Niuean'),
    ('languages', 'zxx', 'en', 'No linguistic content'),
    ('languages', 'nog', 'en', 'Nogai'),
    ('languages', 'non', 'en', 'Norse, Old'),
    ('languages', 'nai', 'en', 'North American Indian languages'),
    ('languages', 'nde', 'en', 'North Ndebele'),
    ('languages', 'frr', 'en', 'Northern Frisian'),
    ('languages', 'sme', 'en', 'Northern Sami'),
    ('languages', 'nso', 'en', 'Northern Sotho'),
    ('languages', 'nor', 'en', 'Norwegian'),
    ('languages', 'nob', 'en', 'Norwegian Bokmål'),
    ('languages', 'nno', 'en', 'Norwegian Nynorsk'),
    ('languages', 'zxx', 'en', 'Not applicable'),
    ('languages', 'nub', 'en', 'Nubian languages'),
    ('languages', 'iii', 'en', 'Nuosu'),
    ('languages', 'nym', 'en', 'Nyamwezi'),
    ('languages', 'nya', 'en', 'Nyanja'),
    ('languages', 'nyn', 'en', 'Nyankole'),
    ('languages', 'nno', 'en', 'Nynorsk, Norwegian'),
    ('languages', 'nyo', 'en', 'Nyoro'),
    ('languages', 'nzi', 'en', 'Nzima'),
    ('languages', 'ile', 'en', 'Occidental'),
    ('languages', 'oci', 'en', 'Occitan (post 1500)'),
    ('languages', 'pro', 'en', 'Occitan, Old (to 1500)'),
    ('languages', 'arc', 'en', 'Official Aramaic (700-300 BCE)'),
    ('languages', 'xal', 'en', 'Oirat'),
    ('languages', 'oji', 'en', 'Ojibwa'),
    ('languages', 'chu', 'en', 'Old Bulgarian'),
    ('languages', 'chu', 'en', 'Old Church Slavonic'),
    ('languages', 'nwc', 'en', 'Old Newari'),
    ('languages', 'chu', 'en', 'Old Slavonic'),
    ('languages', 'ori', 'en', 'Oriya'),
    ('languages', 'orm', 'en', 'Oromo'),
    ('languages', 'osa', 'en', 'Osage'),
    ('languages', 'oss', 'en', 'Ossetian'),
    ('languages', 'oss', 'en', 'Ossetic'),
    ('languages', 'oto', 'en', 'Otomian languages'),
    ('languages', 'pal', 'en', 'Pahlavi'),
    ('languages', 'pau', 'en', 'Palauan'),
    ('languages', 'pli', 'en', 'Pali'),
    ('languages', 'pam', 'en', 'Pampanga'),
    ('languages', 'pag', 'en', 'Pangasinan'),
    ('languages', 'pan', 'en', 'Panjabi'),
    ('languages', 'pap', 'en', 'Papiamento'),
    ('languages', 'paa', 'en', 'Papuan languages'),
    ('languages', 'pus', 'en', 'Pashto'),
    ('languages', 'nso', 'en', 'Pedi'),
    ('languages', 'per', 'en', 'Persian","fa'),
    ('languages', 'peo', 'en', 'Persian, Old (ca.600-400 B.C.)'),
    ('languages', 'phi', 'en', 'Philippine languages'),
    ('languages', 'phn', 'en', 'Phoenician'),
    ('languages', 'fil', 'en', 'Pilipino'),
    ('languages', 'pon', 'en', 'Pohnpeian'),
    ('languages', 'pol', 'en', 'Polish'),
    ('languages', 'por', 'en', 'Portuguese'),
    ('languages', 'pra', 'en', 'Prakrit languages'),
    ('languages', 'pro', 'en', 'Provençal, Old (to 1500)'),
    ('languages', 'pan', 'en', 'Punjabi'),
    ('languages', 'pus', 'en', 'Pushto'),
    ('languages', 'que', 'en', 'Quechua'),
    ('languages', 'raj', 'en', 'Rajasthani'),
    ('languages', 'rap', 'en', 'Rapanui'),
    ('languages', 'rar', 'en', 'Rarotongan'),
    ('languages', 'roa', 'en', 'Romance languages'),
    ('languages', 'rum', 'en', 'Romanian","ro'),
    ('languages', 'roh', 'en', 'Romansh'),
    ('languages', 'rom', 'en', 'Romany'),
    ('languages', 'run', 'en', 'Rundi'),
    ('languages', 'rus', 'en', 'Russian'),
    ('languages', 'kho', 'en', 'Sakan'),
    ('languages', 'sal', 'en', 'Salishan languages'),
    ('languages', 'sam', 'en', 'Samaritan Aramaic'),
    ('languages', 'smi', 'en', 'Sami languages'),
    ('languages', 'smo', 'en', 'Samoan'),
    ('languages', 'sad', 'en', 'Sandawe'),
    ('languages', 'sag', 'en', 'Sango'),
    ('languages', 'san', 'en', 'Sanskrit'),
    ('languages', 'sat', 'en', 'Santali'),
    ('languages', 'srd', 'en', 'Sardinian'),
    ('languages', 'sas', 'en', 'Sasak'),
    ('languages', 'nds', 'en', 'Saxon, Low'),
    ('languages', 'sco', 'en', 'Scots'),
    ('languages', 'gla', 'en', 'Scottish Gaelic'),
    ('languages', 'sel', 'en', 'Selkup'),
    ('languages', 'sem', 'en', 'Semitic languages'),
    ('languages', 'nso', 'en', 'Sepedi'),
    ('languages', 'srp', 'en', 'Serbian'),
    ('languages', 'srr', 'en', 'Serer'),
    ('languages', 'shn', 'en', 'Shan'),
    ('languages', 'sna', 'en', 'Shona'),
    ('languages', 'iii', 'en', 'Sichuan Yi'),
    ('languages', 'scn', 'en', 'Sicilian'),
    ('languages', 'sid', 'en', 'Sidamo'),
    ('languages', 'sgn', 'en', 'Sign Languages'),
    ('languages', 'bla', 'en', 'Siksika'),
    ('languages', 'snd', 'en', 'Sindhi'),
    ('languages', 'sin', 'en', 'Sinhala'),
    ('languages', 'sin', 'en', 'Sinhalese'),
    ('languages', 'sit', 'en', 'Sino-Tibetan languages'),
    ('languages', 'sio', 'en', 'Siouan languages'),
    ('languages', 'sms', 'en', 'Skolt Sami'),
    ('languages', 'den', 'en', 'Slave (Athapascan)'),
    ('languages', 'sla', 'en', 'Slavic languages'),
    ('languages', 'slo', 'en', 'Slovak","sk'),
    ('languages', 'slv', 'en', 'Slovenian'),
    ('languages', 'sog', 'en', 'Sogdian'),
    ('languages', 'som', 'en', 'Somali'),
    ('languages', 'son', 'en', 'Songhai languages'),
    ('languages', 'snk', 'en', 'Soninke'),
    ('languages', 'wen', 'en', 'Sorbian languages'),
    ('languages', 'nso', 'en', 'Sotho, Northern'),
    ('languages', 'sot', 'en', 'Sotho, Southern'),
    ('languages', 'sai', 'en', 'South American Indian languages'),
    ('languages', 'nbl', 'en', 'South Ndebele'),
    ('languages', 'alt', 'en', 'Southern Altai'),
    ('languages', 'sma', 'en', 'Southern Sami'),
    ('languages', 'spa', 'en', 'Spanish'),
    ('languages', 'srn', 'en', 'Sranan Tongo'),
    ('languages', 'zgh', 'en', 'Standard Moroccan Tamazight'),
    ('languages', 'suk', 'en', 'Sukuma'),
    ('languages', 'sux', 'en', 'Sumerian'),
    ('languages', 'sun', 'en', 'Sundanese'),
    ('languages', 'sus', 'en', 'Susu'),
    ('languages', 'swa', 'en', 'Swahili'),
    ('languages', 'ssw', 'en', 'Swati'),
    ('languages', 'swe', 'en', 'Swedish'),
    ('languages', 'gsw', 'en', 'Swiss German'),
    ('languages', 'syr', 'en', 'Syriac'),
    ('languages', 'tgl', 'en', 'Tagalog'),
    ('languages', 'tah', 'en', 'Tahitian'),
    ('languages', 'tai', 'en', 'Tai languages'),
    ('languages', 'tgk', 'en', 'Tajik'),
    ('languages', 'tmh', 'en', 'Tamashek'),
    ('languages', 'tam', 'en', 'Tamil'),
    ('languages', 'tat', 'en', 'Tatar'),
    ('languages', 'tel', 'en', 'Telugu'),
    ('languages', 'ter', 'en', 'Tereno'),
    ('languages', 'tet', 'en', 'Tetum'),
    ('languages', 'tha', 'en', 'Thai'),
    ('languages', 'tib', 'en', 'Tibetan","bo'),
    ('languages', 'tig', 'en', 'Tigre'),
    ('languages', 'tir', 'en', 'Tigrinya'),
    ('languages', 'tem', 'en', 'Timne'),
    ('languages', 'tiv', 'en', 'Tiv'),
    ('languages', 'tlh', 'en', 'tlhIngan-Hol'),
    ('languages', 'tli', 'en', 'Tlingit'),
    ('languages', 'tpi', 'en', 'Tok Pisin'),
    ('languages', 'tkl', 'en', 'Tokelau'),
    ('languages', 'tog', 'en', 'Tonga (Nyasa)'),
    ('languages', 'ton', 'en', 'Tonga (Tonga Islands)'),
    ('languages', 'tsi', 'en', 'Tsimshian'),
    ('languages', 'tso', 'en', 'Tsonga'),
    ('languages', 'tsn', 'en', 'Tswana'),
    ('languages', 'tum', 'en', 'Tumbuka'),
    ('languages', 'tup', 'en', 'Tupi languages'),
    ('languages', 'tur', 'en', 'Turkish'),
    ('languages', 'ota', 'en', 'Turkish, Ottoman (1500-1928)'),
    ('languages', 'tuk', 'en', 'Turkmen'),
    ('languages', 'tvl', 'en', 'Tuvalu'),
    ('languages', 'tyv', 'en', 'Tuvinian'),
    ('languages', 'twi', 'en', 'Twi'),
    ('languages', 'udm', 'en', 'Udmurt'),
    ('languages', 'uga', 'en', 'Ugaritic'),
    ('languages', 'uig', 'en', 'Uighur'),
    ('languages', 'ukr', 'en', 'Ukrainian'),
    ('languages', 'umb', 'en', 'Umbundu'),
    ('languages', 'mis', 'en', 'Uncoded languages'),
    ('languages', 'und', 'en', 'Undetermined'),
    ('languages', 'hsb', 'en', 'Upper Sorbian'),
    ('languages', 'urd', 'en', 'Urdu'),
    ('languages', 'uig', 'en', 'Uyghur'),
    ('languages', 'uzb', 'en', 'Uzbek'),
    ('languages', 'vai', 'en', 'Vai'),
    ('languages', 'cat', 'en', 'Valencian'),
    ('languages', 'ven', 'en', 'Venda'),
    ('languages', 'vie', 'en', 'Vietnamese'),
    ('languages', 'vol', 'en', 'Volapük'),
    ('languages', 'vot', 'en', 'Votic'),
    ('languages', 'wak', 'en', 'Wakashan languages'),
    ('languages', 'wln', 'en', 'Walloon'),
    ('languages', 'war', 'en', 'Waray'),
    ('languages', 'was', 'en', 'Washo'),
    ('languages', 'wel', 'en', 'Welsh","cy'),
    ('languages', 'fry', 'en', 'Western Frisian'),
    ('languages', 'him', 'en', 'Western Pahari languages'),
    ('languages', 'wal', 'en', 'Wolaitta'),
    ('languages', 'wal', 'en', 'Wolaytta'),
    ('languages', 'wol', 'en', 'Wolof'),
    ('languages', 'xho', 'en', 'Xhosa'),
    ('languages', 'sah', 'en', 'Yakut'),
    ('languages', 'yao', 'en', 'Yao'),
    ('languages', 'yap', 'en', 'Yapese'),
    ('languages', 'yid', 'en', 'Yiddish'),
    ('languages', 'yor', 'en', 'Yoruba'),
    ('languages', 'ypk', 'en', 'Yupik languages'),
    ('languages', 'znd', 'en', 'Zande languages'),
    ('languages', 'zap', 'en', 'Zapotec'),
    ('languages', 'zza', 'en', 'Zaza'),
    ('languages', 'zza', 'en', 'Zazaki'),
    ('languages', 'zen', 'en', 'Zenaga'),
    ('languages', 'zha', 'en', 'Zhuang'),
    ('languages', 'zul', 'en', 'Zulu'),
    ('languages', 'zun', 'en', 'Zuni');
