-- patients
INSERT INTO patients (patient_id) VALUES ('554ec907-9f86-4abf-a1fb-7ec211c22611');
INSERT INTO patients (patient_id) VALUES ('ea925eba-98c1-4708-a6b6-c337dfa45900');

-- patient connections
INSERT INTO connections (patient_id, key, value) VALUES ('554ec907-9f86-4abf-a1fb-7ec211c22611', 'name', 'Local User');
INSERT INTO connections (patient_id, key, value) VALUES ('ea925eba-98c1-4708-a6b6-c337dfa45900', 'name', 'Cloud User');

-- patient locations
INSERT INTO locations (patient_id, location_id) VALUES ('554ec907-9f86-4abf-a1fb-7ec211c22611', '2d04b22e-1cc3-46b4-96dd-2bee5bad9ffa');
INSERT INTO locations (patient_id, location_id) VALUES ('ea925eba-98c1-4708-a6b6-c337dfa45900', 'f7e41e48-ec79-4c78-9db6-37c0c4f78326');

-- codes
INSERT INTO codes (category_id, code_id) VALUES
    ('countries', 'AF'),
    ('countries', 'AX'),
    ('countries', 'AL'),
    ('countries', 'DZ'),
    ('countries', 'AS'),
    ('countries', 'AD'),
    ('countries', 'AO'),
    ('countries', 'AI'),
    ('countries', 'AQ'),
    ('countries', 'AG'),
    ('countries', 'AR'),
    ('countries', 'AM'),
    ('countries', 'AW'),
    ('countries', 'AU'),
    ('countries', 'AT'),
    ('countries', 'AZ'),
    ('countries', 'BS'),
    ('countries', 'BH'),
    ('countries', 'BD'),
    ('countries', 'BB'),
    ('countries', 'BY'),
    ('countries', 'BE'),
    ('countries', 'BZ'),
    ('countries', 'BJ'),
    ('countries', 'BM'),
    ('countries', 'BT'),
    ('countries', 'BO'),
    ('countries', 'BA'),
    ('countries', 'BW'),
    ('countries', 'BV'),
    ('countries', 'BR'),
    ('countries', 'VG'),
    ('countries', 'IO'),
    ('countries', 'BN'),
    ('countries', 'BG'),
    ('countries', 'BF'),
    ('countries', 'BI'),
    ('countries', 'KH'),
    ('countries', 'CM'),
    ('countries', 'CA'),
    ('countries', 'CV'),
    ('countries', 'KY'),
    ('countries', 'CF'),
    ('countries', 'TD'),
    ('countries', 'CL'),
    ('countries', 'CN'),
    ('countries', 'HK'),
    ('countries', 'MO'),
    ('countries', 'CX'),
    ('countries', 'CC'),
    ('countries', 'CO'),
    ('countries', 'KM'),
    ('countries', 'CG'),
    ('countries', 'CD'),
    ('countries', 'CK'),
    ('countries', 'CR'),
    ('countries', 'CI'),
    ('countries', 'HR'),
    ('countries', 'CU'),
    ('countries', 'CY'),
    ('countries', 'CZ'),
    ('countries', 'DK'),
    ('countries', 'DJ'),
    ('countries', 'DM'),
    ('countries', 'DO'),
    ('countries', 'EC'),
    ('countries', 'EG'),
    ('countries', 'SV'),
    ('countries', 'GQ'),
    ('countries', 'ER'),
    ('countries', 'EE'),
    ('countries', 'ET'),
    ('countries', 'FK'),
    ('countries', 'FO'),
    ('countries', 'FJ'),
    ('countries', 'FI'),
    ('countries', 'FR'),
    ('countries', 'GF'),
    ('countries', 'PF'),
    ('countries', 'TF'),
    ('countries', 'GA'),
    ('countries', 'GM'),
    ('countries', 'GE'),
    ('countries', 'DE'),
    ('countries', 'GH'),
    ('countries', 'GI'),
    ('countries', 'GR'),
    ('countries', 'GL'),
    ('countries', 'GD'),
    ('countries', 'GP'),
    ('countries', 'GU'),
    ('countries', 'GT'),
    ('countries', 'GG'),
    ('countries', 'GN'),
    ('countries', 'GW'),
    ('countries', 'GY'),
    ('countries', 'HT'),
    ('countries', 'HM'),
    ('countries', 'VA'),
    ('countries', 'HN'),
    ('countries', 'HU'),
    ('countries', 'IS'),
    ('countries', 'IN'),
    ('countries', 'ID'),
    ('countries', 'IR'),
    ('countries', 'IQ'),
    ('countries', 'IE'),
    ('countries', 'IM'),
    ('countries', 'IL'),
    ('countries', 'IT'),
    ('countries', 'JM'),
    ('countries', 'JP'),
    ('countries', 'JE'),
    ('countries', 'JO'),
    ('countries', 'KZ'),
    ('countries', 'KE'),
    ('countries', 'KI'),
    ('countries', 'KP'),
    ('countries', 'KR'),
    ('countries', 'KW'),
    ('countries', 'KG'),
    ('countries', 'LA'),
    ('countries', 'LV'),
    ('countries', 'LB'),
    ('countries', 'LS'),
    ('countries', 'LR'),
    ('countries', 'LY'),
    ('countries', 'LI'),
    ('countries', 'LT'),
    ('countries', 'LU'),
    ('countries', 'MK'),
    ('countries', 'MG'),
    ('countries', 'MW'),
    ('countries', 'MY'),
    ('countries', 'MV'),
    ('countries', 'ML'),
    ('countries', 'MT'),
    ('countries', 'MH'),
    ('countries', 'MQ'),
    ('countries', 'MR'),
    ('countries', 'MU'),
    ('countries', 'YT'),
    ('countries', 'MX'),
    ('countries', 'FM'),
    ('countries', 'MD'),
    ('countries', 'MC'),
    ('countries', 'MN'),
    ('countries', 'ME'),
    ('countries', 'MS'),
    ('countries', 'MA'),
    ('countries', 'MZ'),
    ('countries', 'MM'),
    ('countries', 'NA'),
    ('countries', 'NR'),
    ('countries', 'NP'),
    ('countries', 'NL'),
    ('countries', 'AN'),
    ('countries', 'NC'),
    ('countries', 'NZ'),
    ('countries', 'NI'),
    ('countries', 'NE'),
    ('countries', 'NG'),
    ('countries', 'NU'),
    ('countries', 'NF'),
    ('countries', 'MP'),
    ('countries', 'NO'),
    ('countries', 'OM'),
    ('countries', 'PK'),
    ('countries', 'PW'),
    ('countries', 'PS'),
    ('countries', 'PA'),
    ('countries', 'PG'),
    ('countries', 'PY'),
    ('countries', 'PE'),
    ('countries', 'PH'),
    ('countries', 'PN'),
    ('countries', 'PL'),
    ('countries', 'PT'),
    ('countries', 'PR'),
    ('countries', 'QA'),
    ('countries', 'RE'),
    ('countries', 'RO'),
    ('countries', 'RU'),
    ('countries', 'RW'),
    ('countries', 'BL'),
    ('countries', 'SH'),
    ('countries', 'KN'),
    ('countries', 'LC'),
    ('countries', 'MF'),
    ('countries', 'PM'),
    ('countries', 'VC'),
    ('countries', 'WS'),
    ('countries', 'SM'),
    ('countries', 'ST'),
    ('countries', 'SA'),
    ('countries', 'SN'),
    ('countries', 'RS'),
    ('countries', 'SC'),
    ('countries', 'SL'),
    ('countries', 'SG'),
    ('countries', 'SK'),
    ('countries', 'SI'),
    ('countries', 'SB'),
    ('countries', 'SO'),
    ('countries', 'ZA'),
    ('countries', 'GS'),
    ('countries', 'SS'),
    ('countries', 'ES'),
    ('countries', 'LK'),
    ('countries', 'SD'),
    ('countries', 'SR'),
    ('countries', 'SJ'),
    ('countries', 'SZ'),
    ('countries', 'SE'),
    ('countries', 'CH'),
    ('countries', 'SY'),
    ('countries', 'TW'),
    ('countries', 'TJ'),
    ('countries', 'TZ'),
    ('countries', 'TH'),
    ('countries', 'TL'),
    ('countries', 'TG'),
    ('countries', 'TK'),
    ('countries', 'TO'),
    ('countries', 'TT'),
    ('countries', 'TN'),
    ('countries', 'TR'),
    ('countries', 'TM'),
    ('countries', 'TC'),
    ('countries', 'TV'),
    ('countries', 'UG'),
    ('countries', 'UA'),
    ('countries', 'AE'),
    ('countries', 'GB'),
    ('countries', 'US'),
    ('countries', 'UM'),
    ('countries', 'UY'),
    ('countries', 'UZ'),
    ('countries', 'VU'),
    ('countries', 'VE'),
    ('countries', 'VN'),
    ('countries', 'VI'),
    ('countries', 'WF'),
    ('countries', 'EH'),
    ('countries', 'YE'),
    ('countries', 'ZM'),
    ('countries', 'ZW'),

    ('languages', 'ara'),
    ('languages', 'eng'),
    ('languages', 'fre'),
    ('languages', 'ger'),
    ('languages', 'per'),
    ('languages', 'urd'),
    ('languages', 'slv'),
    ('languages', 'spa'),

    ('licenses', 'dl-a'),
    ('licenses', 'dl-b'),
    ('licenses', 'dl-c'),
    ('licenses', 'dl-d'),

    -- Concept 224083004
    ('maritalStatus', 'SNOMED-33553000'),
    ('maritalStatus', 'SNOMED-87915002'),
    ('maritalStatus', 'SNOMED-20295000'),
    ('maritalStatus', 'SNOMED-54986009'),
    ('maritalStatus', 'SNOMED-125681006'),

    ('gender', 'CODED-at0310'),
    ('gender', 'CODED-at0311'),
    ('gender', 'CODED-at0312'),
    ('gender', 'CODED-at0313'),

    ('documentTypes', 'un-id'),
    ('documentTypes', 'syrian-id'),

    ('childCommunication', 'smiles'),
    ('childCommunication', 'babbles'),
    ('childCommunication', 'pointsToBody'),
    ('childCommunication', 'knowsOwnNams'),
    ('childCommunication', 'pointsToBodyParts'),
    ('childCommunication', 'simplesWords'),
    ('childCommunication', 'sentences'),

    ('babyFood', 'breastMilk'),
    ('babyFood', 'babyFood'),
    ('babyFood', 'formula'),
    ('babyFood', 'regularFood'),

    ('deliveryType', 'natural'),
    ('deliveryType', 'ceasarean'),

    ('education', 'primary'),
    ('education', 'terciary'),
    ('education', 'secondary'),

    ('diagnosis', 'SNOMED-123123'),
    ('diagnosis', 'SNOMED-234234'),
    ('diagnosis', 'SNOMED-345345');

INSERT INTO code_titles (category_id, code_id, locale, title) VALUES
    ('countries', 'AF', 'en', 'Afghanistan'),
    ('countries', 'AX', 'en', 'Aland Islands'),
    ('countries', 'AL', 'en', 'Albania'),
    ('countries', 'DZ', 'en', 'Algeria'),
    ('countries', 'AS', 'en', 'American Samoa'),
    ('countries', 'AD', 'en', 'Andorra'),
    ('countries', 'AO', 'en', 'Angola'),
    ('countries', 'AI', 'en', 'Anguilla'),
    ('countries', 'AQ', 'en', 'Antarctica'),
    ('countries', 'AG', 'en', 'Antigua and Barbuda'),
    ('countries', 'AR', 'en', 'Argentina'),
    ('countries', 'AM', 'en', 'Armenia'),
    ('countries', 'AW', 'en', 'Aruba'),
    ('countries', 'AU', 'en', 'Australia'),
    ('countries', 'AT', 'en', 'Austria'),
    ('countries', 'AZ', 'en', 'Azerbaijan'),
    ('countries', 'BS', 'en', 'Bahamas'),
    ('countries', 'BH', 'en', 'Bahrain'),
    ('countries', 'BD', 'en', 'Bangladesh'),
    ('countries', 'BB', 'en', 'Barbados'),
    ('countries', 'BY', 'en', 'Belarus'),
    ('countries', 'BE', 'en', 'Belgium'),
    ('countries', 'BZ', 'en', 'Belize'),
    ('countries', 'BJ', 'en', 'Benin'),
    ('countries', 'BM', 'en', 'Bermuda'),
    ('countries', 'BT', 'en', 'Bhutan'),
    ('countries', 'BO', 'en', 'Bolivia'),
    ('countries', 'BA', 'en', 'Bosnia and Herzegovina'),
    ('countries', 'BW', 'en', 'Botswana'),
    ('countries', 'BV', 'en', 'Bouvet Island'),
    ('countries', 'BR', 'en', 'Brazil'),
    ('countries', 'VG', 'en', 'British Virgin Islands'),
    ('countries', 'IO', 'en', 'British Indian Ocean Territory'),
    ('countries', 'BN', 'en', 'Brunei Darussalam'),
    ('countries', 'BG', 'en', 'Bulgaria'),
    ('countries', 'BF', 'en', 'Burkina Faso'),
    ('countries', 'BI', 'en', 'Burundi'),
    ('countries', 'KH', 'en', 'Cambodia'),
    ('countries', 'CM', 'en', 'Cameroon'),
    ('countries', 'CA', 'en', 'Canada'),
    ('countries', 'CV', 'en', 'Cape Verde'),
    ('countries', 'KY', 'en', 'Cayman Islands'),
    ('countries', 'CF', 'en', 'Central African Republic'),
    ('countries', 'TD', 'en', 'Chad'),
    ('countries', 'CL', 'en', 'Chile'),
    ('countries', 'CN', 'en', 'China'),
    ('countries', 'HK', 'en', 'Hong Kong, SAR China'),
    ('countries', 'MO', 'en', 'Macao, SAR China'),
    ('countries', 'CX', 'en', 'Christmas Island'),
    ('countries', 'CC', 'en', 'Cocos (Keeling) Islands'),
    ('countries', 'CO', 'en', 'Colombia'),
    ('countries', 'KM', 'en', 'Comoros'),
    ('countries', 'CG', 'en', 'Congo (Brazzaville)'),
    ('countries', 'CD', 'en', 'Congo, (Kinshasa)'),
    ('countries', 'CK', 'en', 'Cook Islands'),
    ('countries', 'CR', 'en', 'Costa Rica'),
    ('countries', 'CI', 'en', 'Côte d''Ivoire'),
    ('countries', 'HR', 'en', 'Croatia'),
    ('countries', 'CU', 'en', 'Cuba'),
    ('countries', 'CY', 'en', 'Cyprus'),
    ('countries', 'CZ', 'en', 'Czech Republic'),
    ('countries', 'DK', 'en', 'Denmark'),
    ('countries', 'DJ', 'en', 'Djibouti'),
    ('countries', 'DM', 'en', 'Dominica'),
    ('countries', 'DO', 'en', 'Dominican Republic'),
    ('countries', 'EC', 'en', 'Ecuador'),
    ('countries', 'EG', 'en', 'Egypt'),
    ('countries', 'SV', 'en', 'El Salvador'),
    ('countries', 'GQ', 'en', 'Equatorial Guinea'),
    ('countries', 'ER', 'en', 'Eritrea'),
    ('countries', 'EE', 'en', 'Estonia'),
    ('countries', 'ET', 'en', 'Ethiopia'),
    ('countries', 'FK', 'en', 'Falkland Islands (Malvinas)'),
    ('countries', 'FO', 'en', 'Faroe Islands'),
    ('countries', 'FJ', 'en', 'Fiji'),
    ('countries', 'FI', 'en', 'Finland'),
    ('countries', 'FR', 'en', 'France'),
    ('countries', 'GF', 'en', 'French Guiana'),
    ('countries', 'PF', 'en', 'French Polynesia'),
    ('countries', 'TF', 'en', 'French Southern Territories'),
    ('countries', 'GA', 'en', 'Gabon'),
    ('countries', 'GM', 'en', 'Gambia'),
    ('countries', 'GE', 'en', 'Georgia'),
    ('countries', 'DE', 'en', 'Germany'),
    ('countries', 'GH', 'en', 'Ghana'),
    ('countries', 'GI', 'en', 'Gibraltar'),
    ('countries', 'GR', 'en', 'Greece'),
    ('countries', 'GL', 'en', 'Greenland'),
    ('countries', 'GD', 'en', 'Grenada'),
    ('countries', 'GP', 'en', 'Guadeloupe'),
    ('countries', 'GU', 'en', 'Guam'),
    ('countries', 'GT', 'en', 'Guatemala'),
    ('countries', 'GG', 'en', 'Guernsey'),
    ('countries', 'GN', 'en', 'Guinea'),
    ('countries', 'GW', 'en', 'Guinea-Bissau'),
    ('countries', 'GY', 'en', 'Guyana'),
    ('countries', 'HT', 'en', 'Haiti'),
    ('countries', 'HM', 'en', 'Heard and Mcdonald Islands'),
    ('countries', 'VA', 'en', 'Holy See (Vatican City State)'),
    ('countries', 'HN', 'en', 'Honduras'),
    ('countries', 'HU', 'en', 'Hungary'),
    ('countries', 'IS', 'en', 'Iceland'),
    ('countries', 'IN', 'en', 'India'),
    ('countries', 'ID', 'en', 'Indonesia'),
    ('countries', 'IR', 'en', 'Iran, Islamic Republic of'),
    ('countries', 'IQ', 'en', 'Iraq'),
    ('countries', 'IE', 'en', 'Ireland'),
    ('countries', 'IM', 'en', 'Isle of Man'),
    ('countries', 'IL', 'en', 'Israel'),
    ('countries', 'IT', 'en', 'Italy'),
    ('countries', 'JM', 'en', 'Jamaica'),
    ('countries', 'JP', 'en', 'Japan'),
    ('countries', 'JE', 'en', 'Jersey'),
    ('countries', 'JO', 'en', 'Jordan'),
    ('countries', 'KZ', 'en', 'Kazakhstan'),
    ('countries', 'KE', 'en', 'Kenya'),
    ('countries', 'KI', 'en', 'Kiribati'),
    ('countries', 'KP', 'en', 'Korea (North)'),
    ('countries', 'KR', 'en', 'Korea (South)'),
    ('countries', 'KW', 'en', 'Kuwait'),
    ('countries', 'KG', 'en', 'Kyrgyzstan'),
    ('countries', 'LA', 'en', 'Lao PDR'),
    ('countries', 'LV', 'en', 'Latvia'),
    ('countries', 'LB', 'en', 'Lebanon'),
    ('countries', 'LS', 'en', 'Lesotho'),
    ('countries', 'LR', 'en', 'Liberia'),
    ('countries', 'LY', 'en', 'Libya'),
    ('countries', 'LI', 'en', 'Liechtenstein'),
    ('countries', 'LT', 'en', 'Lithuania'),
    ('countries', 'LU', 'en', 'Luxembourg'),
    ('countries', 'MK', 'en', 'Macedonia, Republic of'),
    ('countries', 'MG', 'en', 'Madagascar'),
    ('countries', 'MW', 'en', 'Malawi'),
    ('countries', 'MY', 'en', 'Malaysia'),
    ('countries', 'MV', 'en', 'Maldives'),
    ('countries', 'ML', 'en', 'Mali'),
    ('countries', 'MT', 'en', 'Malta'),
    ('countries', 'MH', 'en', 'Marshall Islands'),
    ('countries', 'MQ', 'en', 'Martinique'),
    ('countries', 'MR', 'en', 'Mauritania'),
    ('countries', 'MU', 'en', 'Mauritius'),
    ('countries', 'YT', 'en', 'Mayotte'),
    ('countries', 'MX', 'en', 'Mexico'),
    ('countries', 'FM', 'en', 'Micronesia, Federated States of'),
    ('countries', 'MD', 'en', 'Moldova'),
    ('countries', 'MC', 'en', 'Monaco'),
    ('countries', 'MN', 'en', 'Mongolia'),
    ('countries', 'ME', 'en', 'Montenegro'),
    ('countries', 'MS', 'en', 'Montserrat'),
    ('countries', 'MA', 'en', 'Morocco'),
    ('countries', 'MZ', 'en', 'Mozambique'),
    ('countries', 'MM', 'en', 'Myanmar'),
    ('countries', 'NA', 'en', 'Namibia'),
    ('countries', 'NR', 'en', 'Nauru'),
    ('countries', 'NP', 'en', 'Nepal'),
    ('countries', 'NL', 'en', 'Netherlands'),
    ('countries', 'AN', 'en', 'Netherlands Antilles'),
    ('countries', 'NC', 'en', 'New Caledonia'),
    ('countries', 'NZ', 'en', 'New Zealand'),
    ('countries', 'NI', 'en', 'Nicaragua'),
    ('countries', 'NE', 'en', 'Niger'),
    ('countries', 'NG', 'en', 'Nigeria'),
    ('countries', 'NU', 'en', 'Niue'),
    ('countries', 'NF', 'en', 'Norfolk Island'),
    ('countries', 'MP', 'en', 'Northern Mariana Islands'),
    ('countries', 'NO', 'en', 'Norway'),
    ('countries', 'OM', 'en', 'Oman'),
    ('countries', 'PK', 'en', 'Pakistan'),
    ('countries', 'PW', 'en', 'Palau'),
    ('countries', 'PS', 'en', 'Palestinian Territory'),
    ('countries', 'PA', 'en', 'Panama'),
    ('countries', 'PG', 'en', 'Papua New Guinea'),
    ('countries', 'PY', 'en', 'Paraguay'),
    ('countries', 'PE', 'en', 'Peru'),
    ('countries', 'PH', 'en', 'Philippines'),
    ('countries', 'PN', 'en', 'Pitcairn'),
    ('countries', 'PL', 'en', 'Poland'),
    ('countries', 'PT', 'en', 'Portugal'),
    ('countries', 'PR', 'en', 'Puerto Rico'),
    ('countries', 'QA', 'en', 'Qatar'),
    ('countries', 'RE', 'en', 'Réunion'),
    ('countries', 'RO', 'en', 'Romania'),
    ('countries', 'RU', 'en', 'Russian Federation'),
    ('countries', 'RW', 'en', 'Rwanda'),
    ('countries', 'BL', 'en', 'Saint-Barthélemy'),
    ('countries', 'SH', 'en', 'Saint Helena'),
    ('countries', 'KN', 'en', 'Saint Kitts and Nevis'),
    ('countries', 'LC', 'en', 'Saint Lucia'),
    ('countries', 'MF', 'en', 'Saint-Martin (French part)'),
    ('countries', 'PM', 'en', 'Saint Pierre and Miquelon'),
    ('countries', 'VC', 'en', 'Saint Vincent and Grenadines'),
    ('countries', 'WS', 'en', 'Samoa'),
    ('countries', 'SM', 'en', 'San Marino'),
    ('countries', 'ST', 'en', 'Sao Tome and Principe'),
    ('countries', 'SA', 'en', 'Saudi Arabia'),
    ('countries', 'SN', 'en', 'Senegal'),
    ('countries', 'RS', 'en', 'Serbia'),
    ('countries', 'SC', 'en', 'Seychelles'),
    ('countries', 'SL', 'en', 'Sierra Leone'),
    ('countries', 'SG', 'en', 'Singapore'),
    ('countries', 'SK', 'en', 'Slovakia'),
    ('countries', 'SI', 'en', 'Slovenia'),
    ('countries', 'SB', 'en', 'Solomon Islands'),
    ('countries', 'SO', 'en', 'Somalia'),
    ('countries', 'ZA', 'en', 'South Africa'),
    ('countries', 'GS', 'en', 'South Georgia and the South Sandwich Islands'),
    ('countries', 'SS', 'en', 'South Sudan'),
    ('countries', 'ES', 'en', 'Spain'),
    ('countries', 'LK', 'en', 'Sri Lanka'),
    ('countries', 'SD', 'en', 'Sudan'),
    ('countries', 'SR', 'en', 'Suriname'),
    ('countries', 'SJ', 'en', 'Svalbard and Jan Mayen Islands'),
    ('countries', 'SZ', 'en', 'Swaziland'),
    ('countries', 'SE', 'en', 'Sweden'),
    ('countries', 'CH', 'en', 'Switzerland'),
    ('countries', 'SY', 'en', 'Syrian Arab Republic (Syria)'),
    ('countries', 'TW', 'en', 'Taiwan, Republic of China'),
    ('countries', 'TJ', 'en', 'Tajikistan'),
    ('countries', 'TZ', 'en', 'Tanzania, United Republic of'),
    ('countries', 'TH', 'en', 'Thailand'),
    ('countries', 'TL', 'en', 'Timor-Leste'),
    ('countries', 'TG', 'en', 'Togo'),
    ('countries', 'TK', 'en', 'Tokelau'),
    ('countries', 'TO', 'en', 'Tonga'),
    ('countries', 'TT', 'en', 'Trinidad and Tobago'),
    ('countries', 'TN', 'en', 'Tunisia'),
    ('countries', 'TR', 'en', 'Turkey'),
    ('countries', 'TM', 'en', 'Turkmenistan'),
    ('countries', 'TC', 'en', 'Turks and Caicos Islands'),
    ('countries', 'TV', 'en', 'Tuvalu'),
    ('countries', 'UG', 'en', 'Uganda'),
    ('countries', 'UA', 'en', 'Ukraine'),
    ('countries', 'AE', 'en', 'United Arab Emirates'),
    ('countries', 'GB', 'en', 'United Kingdom'),
    ('countries', 'US', 'en', 'United States of America'),
    ('countries', 'UM', 'en', 'US Minor Outlying Islands'),
    ('countries', 'UY', 'en', 'Uruguay'),
    ('countries', 'UZ', 'en', 'Uzbekistan'),
    ('countries', 'VU', 'en', 'Vanuatu'),
    ('countries', 'VE', 'en', 'Venezuela (Bolivarian Republic)'),
    ('countries', 'VN', 'en', 'Viet Nam'),
    ('countries', 'VI', 'en', 'Virgin Islands, US'),
    ('countries', 'WF', 'en', 'Wallis and Futuna Islands'),
    ('countries', 'EH', 'en', 'Western Sahara'),
    ('countries', 'YE', 'en', 'Yemen'),
    ('countries', 'ZM', 'en', 'Zambia'),
    ('countries', 'ZW', 'en', 'Zimbabwe'),

    ('languages', 'ara', 'en', 'Arabic'),
    ('languages', 'eng', 'en', 'English'),
    ('languages', 'fre', 'en', 'French'),
    ('languages', 'ger', 'en', 'German'),
    ('languages', 'per', 'en', 'Persian'),
    ('languages', 'urd', 'en', 'Urdu'),
    ('languages', 'slv', 'en', 'Slovenian'),
    ('languages', 'spa', 'en', 'Spanish'),

    ('licenses', 'dl-a', 'en', 'Category A driving license'),
    ('licenses', 'dl-b', 'en', 'Category B driving license'),
    ('licenses', 'dl-c', 'en', 'Category C driving license'),
    ('licenses', 'dl-d', 'en', 'Category D driving license'),

    -- Concept 224083004
    ('maritalStatus', 'SNOMED-33553000', 'en', 'Widowed'),
    ('maritalStatus', 'SNOMED-87915002', 'en', 'Married'),
    ('maritalStatus', 'SNOMED-20295000', 'en', 'Divorced'),
    ('maritalStatus', 'SNOMED-54986009', 'en', 'Engaged'),
    ('maritalStatus', 'SNOMED-125681006', 'en', 'Single'),

    ('gender', 'CODED-at0310', 'en', 'Male'),
    ('gender', 'CODED-at0311', 'en', 'Female'),
    ('gender', 'CODED-at0312', 'en', 'Intersex or indeterminate'),
    ('gender', 'CODED-at0313', 'en', 'Not declared/inadequately described'),

    ('documentTypes', 'un-id', 'en', 'UN ID'),
    ('documentTypes', 'syrian-id', 'en', 'Syrian ID'),

    ('childCommunication', 'smiles', 'en', 'Smiles'),
    ('childCommunication', 'babbles', 'en', 'Babbles'),
    ('childCommunication', 'pointsToBody', 'en', 'Can point to body'),
    ('childCommunication', 'knowsOwnNams', 'en', 'Knows own name'),
    ('childCommunication', 'pointsToBodyParts', 'en', 'Can point to body parts'),
    ('childCommunication', 'simplesWords', 'en', 'Can say simple words'),
    ('childCommunication', 'sentences', 'en', 'Speaks in sentence'),

    ('babyFood', 'breastMilk', 'en', 'Breast milk'),
    ('babyFood', 'babyFood', 'en', 'Baby food'),
    ('babyFood', 'formula', 'en', 'Formula'),
    ('babyFood', 'regularFood', 'en', 'Regular food'),

    ('deliveryType', 'natural', 'en', 'Natural'),
    ('deliveryType', 'ceasarean', 'en', 'Ceasarean'),

    ('education', 'primary', 'en', 'primary'),
    ('education', 'terciary', 'en', 'terciary'),
    ('education', 'secondary', 'en', 'secondary'),

    ('diagnosis', 'SNOMED-123123', 'en', 'knee pain'),
    ('diagnosis', 'SNOMED-234234', 'en', 'headache'),
    ('diagnosis', 'SNOMED-345345', 'en', 'trombognosis');
